#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PASS=0
FAIL=0
ERRORS=""

pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; ERRORS="${ERRORS}\n--- $1 ---\n${2:-unknown}\n"; FAIL=$((FAIL + 1)); }

make_stub_harness() {
  local dir="$1"
  mkdir -p "$dir"
  cat > "$dir/harness-stub" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
echo "$0 $*" >> "${HARNESS_LOG:?HARNESS_LOG required}"
args_json=""
args_file=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --args-json) args_json="$2"; shift 2 ;;
    --args-file) args_file="$2"; shift 2 ;;
    *) shift ;;
  esac
done
if [ -n "$args_file" ]; then
  cp "$args_file" "${HARNESS_ARGS_CAPTURE:?HARNESS_ARGS_CAPTURE required}"
else
  printf '%s' "$args_json" > "${HARNESS_ARGS_CAPTURE:?HARNESS_ARGS_CAPTURE required}"
fi
python3 - "${HARNESS_ARGS_CAPTURE}" <<'PY'
import json, sys
args=json.load(open(sys.argv[1]))
schema=str(args.get('schema',''))
inp=args.get('input') or {}
if schema.endswith('vote-ballot.schema.json'):
 print(json.dumps({'chosen_option':'approve','verdict':'approve','confidence':0.9,'reasoning':'stub','scores':{'overall':0.9},'suggestions':[]}))
elif schema.endswith('quality-gate.schema.json'):
 print(json.dumps({'pass':True,'score':9,'summary':'stub pass','blocking_issues':[],'warnings':[]}))
elif schema.endswith('generated-task.schema.json'):
 tasks=inp.get('tasks') or []
 print(json.dumps([{**t, 'subtasks':[{'id': int(t.get('id', 0))*10+1, 'title':'Subtask', 'description':'Generated by stub', 'dependencies':[]}]} for t in tasks]))
else:
 print(json.dumps({'ok': True, 'schema': schema}))
PY
SH
  chmod +x "$dir/harness-stub"
}

echo "=== harness-agnostic LLM invocation ==="
TMPDIR_TEST="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_TEST"' EXIT
make_stub_harness "$TMPDIR_TEST/bin"
export PATH="$TMPDIR_TEST/bin:$PATH"
export HARNESS_LOG="$TMPDIR_TEST/harness.log"
export HARNESS_ARGS_CAPTURE="$TMPDIR_TEST/args.json"
export CTO_LLM_INVOKE_CMD="harness-stub"

ARGS='{"prompt":"p","input":{"stage":"unit"},"schema":"intake/schemas/quality-gate.schema.json","provider":"stub","model":"stub"}'
if output=$("$ROOT/intake/scripts/llm-invoke.sh" --tool llm-task --action json --args-json "$ARGS" 2>&1); then
  JSON_INPUT="$output" python3 - <<'PY' && pass "llm-invoke.sh delegates to CTO_LLM_INVOKE_CMD" || fail "llm-invoke.sh output should be quality-gate JSON" "$output"
import json, sys
import os
raw=os.environ['JSON_INPUT']
start=raw.find('{')
assert start >= 0, raw
d=json.loads(raw[start:])
assert d['pass'] is True and d['score'] == 9
PY
else
  fail "llm-invoke.sh should call custom harness" "$output"
fi
if grep -q 'harness-stub --tool llm-task --action json --args-json' "$HARNESS_LOG"; then
  pass "custom harness receives original llm-task args"
else
  fail "custom harness did not receive expected args" "$(cat "$HARNESS_LOG" 2>/dev/null || true)"
fi

if output=$(env -u CTO_LLM_INVOKE_CMD -u CTO_LLM_INVOKE_BACKEND PATH="$TMPDIR_TEST/bin:/usr/local/bin:/usr/bin:/bin" "$ROOT/intake/scripts/llm-invoke.sh" --tool llm-task --action json --args-json "$ARGS" 2>&1); then
  fail "llm-invoke.sh should fail clearly when no harness is available" "$output"
elif grep -qi 'No LLM harness backend is available\|ACPX binary not found\|Set one of:' <<<"$output"; then
  pass "missing harness produces actionable error"
else
  fail "missing harness error should be actionable" "$output"
fi

export CTO_LLM_INVOKE_CMD="harness-stub"
export HARNESS_LOG="$TMPDIR_TEST/inline-vote.log"
export HARNESS_ARGS_CAPTURE="$TMPDIR_TEST/inline-vote-args.json"
printf 'candidate content\n' > "$TMPDIR_TEST/content.txt"
if output=$(CTO_LLM_INVOKE_CMD="$TMPDIR_TEST/bin/harness-stub" PATH="$TMPDIR_TEST/bin:$PATH" WORKSPACE="$ROOT" "$ROOT/intake/scripts/inline-vote.sh" "$TMPDIR_TEST/content.txt" "quality" stub model stub model stub model 2>&1); then
  JSON_INPUT="$output" python3 - <<'PY' && pass "inline-vote uses harness adapter" || fail "inline-vote should emit tally wrapper" "$output"
import json, sys
import os
raw=os.environ['JSON_INPUT']
start=raw.find('{')
assert start >= 0, raw
d=json.loads(raw[start:])
assert d['output'][0]['verdict'] == 'approve'
PY
else
  fail "inline-vote should not require openclaw.invoke" "$output"
fi
if grep -q 'harness-stub --tool llm-task --action json --args-file' "$HARNESS_LOG"; then
  pass "inline-vote delegates voters through configured harness"
else
  fail "inline-vote did not call configured harness" "$(cat "$HARNESS_LOG" 2>/dev/null || true)"
fi

export HARNESS_LOG="$TMPDIR_TEST/quality-gate.log"
export HARNESS_ARGS_CAPTURE="$TMPDIR_TEST/quality-gate-args.json"
printf 'artifact bundle\n' > "$TMPDIR_TEST/artifacts.txt"
if output=$(CTO_LLM_INVOKE_CMD="$TMPDIR_TEST/bin/harness-stub" WORKSPACE="$ROOT" "$ROOT/intake/scripts/quality-gate.sh" --stage unit --input-file "$TMPDIR_TEST/artifacts.txt" --provider stub --model stub 2>&1); then
  JSON_INPUT="$output" python3 - <<'PY' && pass "quality-gate uses harness adapter" || fail "quality-gate should emit quality JSON" "$output"
import json, sys
import os
raw=os.environ['JSON_INPUT']
start=raw.find('{')
assert start >= 0, raw
d=json.loads(raw[start:])
assert d['pass'] is True and d['score'] == 9
PY
else
  fail "quality-gate should not require openclaw retry wrapper" "$output"
fi

if [ "$FAIL" -ne 0 ]; then
  echo ""
  echo "FAILURES:$ERRORS"
  exit 1
fi

echo ""
echo "Harness-agnostic tests passed: $PASS"
