#!/usr/bin/env -S deno run --allow-net --allow-write --allow-read --allow-env
// codegen.ts — Reads the MCP tool catalog and generates typed TypeScript wrappers.
// Runs at agent pod startup to populate /.cto-tools/servers/.

// ─── Config ──────────────────────────────────────────────────────────────────

const env = (key: string, fallback: string): string =>
  Deno.env.get(key) ?? fallback;

const TOOLS_SERVER_URL = env(
  "TOOLS_SERVER_URL",
  "http://cto-tools.cto.svc.cluster.local:3000/mcp",
);
const OUTPUT_DIR = env("CTO_TOOLS_OUTPUT", "/.cto-tools");
const AGENT_ID = Deno.env.get("CTO_AGENT_ID") ?? "";
const AGENT_PREWARM = Deno.env.get("CTO_AGENT_PREWARM") ?? "";

const CLIENT_CONFIG_PATH = env(
  "CLIENT_CONFIG_PATH",
  "/task-files/client-config.json",
);

const RETRY_COUNT = 5;
const RETRY_DELAY_MS = 3_000;
const LOCAL_DISCOVERY_TIMEOUT_MS = 30_000;

const GENERATED_HEADER = "// Auto-generated by codegen.ts — do not edit manually.";

// ─── Types ───────────────────────────────────────────────────────────────────

interface JsonRpcResponse<T = unknown> {
  jsonrpc: "2.0";
  id: number;
  result?: T;
  error?: { code: number; message: string; data?: unknown };
}

export interface ToolDef {
  name: string;
  description?: string;
  inputSchema?: JsonSchema;
}

export interface JsonSchema {
  type?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  description?: string;
  enum?: unknown[];
}

interface ToolsListResult {
  tools: ToolDef[];
}

// ─── Client Config (local stdio servers) ────────────────────────────────────

interface LocalServerConfig {
  command: string;
  args: string[];
  tools: string[];
  workingDirectory?: string;
  env?: Record<string, string>;
}

interface ClientConfig {
  remoteTools: string[];
  localServers: Record<string, LocalServerConfig>;
}

function loadClientConfig(): ClientConfig | null {
  try {
    const text = Deno.readTextFileSync(CLIENT_CONFIG_PATH);
    return JSON.parse(text) as ClientConfig;
  } catch {
    return null;
  }
}

export interface ParsedTool {
  fullName: string;
  serverPrefix: string;
  funcName: string;
  description?: string;
  inputSchema?: JsonSchema;
}

// ─── JSON Schema → TypeScript ────────────────────────────────────────────────

export function jsonSchemaToTsType(schema: JsonSchema | undefined): string {
  if (!schema || !schema.type) return "unknown";

  switch (schema.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "array": {
      if (schema.items) {
        const inner = jsonSchemaToTsType(schema.items);
        return `Array<${inner}>`;
      }
      return "unknown[]";
    }
    case "object": {
      if (schema.properties) {
        const required = new Set(schema.required ?? []);
        const entries = Object.entries(schema.properties).map(([key, prop]) => {
          const opt = required.has(key) ? "" : "?";
          const type = jsonSchemaToTsType(prop);
          return `${key}${opt}: ${type}`;
        });
        return `{ ${entries.join("; ")} }`;
      }
      return "Record<string, unknown>";
    }
    default:
      return "unknown";
  }
}

export function buildArgsType(schema: JsonSchema | undefined): string {
  if (!schema || !schema.properties) return "Record<string, unknown>";

  const required = new Set(schema.required ?? []);
  const entries = Object.entries(schema.properties).map(([key, prop]) => {
    const opt = required.has(key) ? "" : "?";
    const type = jsonSchemaToTsType(prop);
    return `${key}${opt}: ${type}`;
  });
  return `{ ${entries.join("; ")} }`;
}

// ─── Tool name parsing ──────────────────────────────────────────────────────

export function parseTool(tool: ToolDef): ParsedTool {
  const idx = tool.name.indexOf("_");
  const serverPrefix = idx > 0 ? tool.name.slice(0, idx) : tool.name;
  const funcName = idx > 0 ? tool.name.slice(idx + 1) : "call";
  return {
    fullName: tool.name,
    serverPrefix,
    funcName,
    description: tool.description,
    inputSchema: tool.inputSchema as JsonSchema | undefined,
  };
}

// ─── Code generation ─────────────────────────────────────────────────────────

export function generateJsDoc(tool: ParsedTool): string {
  const lines: string[] = [];
  if (tool.description) {
    lines.push(`/** ${tool.description}`);
  } else {
    lines.push("/**");
  }

  if (tool.inputSchema?.properties) {
    if (lines.length === 1 && tool.description) lines[0] += "\n *";
    for (const [key, prop] of Object.entries(tool.inputSchema.properties)) {
      const desc = (prop as JsonSchema).description;
      if (desc) {
        lines.push(` * @param args.${key} - ${desc}`);
      }
    }
  }

  lines.push(" */");
  return lines.join("\n");
}

export function generateToolFile(tool: ParsedTool): string {
  const argsType = buildArgsType(tool.inputSchema);
  const jsDoc = generateJsDoc(tool);

  return `${GENERATED_HEADER}
import { callTool } from "../../mcp.ts";

${jsDoc}
export async function ${tool.funcName}(
  args: ${argsType}
): Promise<unknown> {
  return callTool("${tool.fullName}", args);
}
`;
}

export function generateServerIndex(funcNames: string[]): string {
  const sorted = [...funcNames].sort();
  const exports = sorted
    .map((fn) => `export { ${fn} } from "./${fn}.ts";`)
    .join("\n");
  return `${GENERATED_HEADER}\n${exports}\n`;
}

export function generateDenoJson(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        strict: true,
        noImplicitAny: true,
      },
      permissions: {
        net: ["cto-tools.cto.svc.cluster.local", "localhost"],
        read: ["/workspace", "/.cto-tools"],
        write: ["/tmp"],
        env: [
          "TOOLS_SERVER_URL",
          "LOCAL_TOOLS_URL",
          "CTO_AGENT_ID",
          "CTO_AGENT_PREWARM",
          "LOCAL_TOOLS",
        ],
      },
    },
    null,
    2,
  ) + "\n";
}

export function generateReadme(serverNames: string[]): string {
  const sorted = [...serverNames].sort();
  const serverList = sorted.map((s) => `- \`${s}/\``).join("\n");
  const example = sorted[0] ?? "github";

  return `# CTO Tools — Generated SDK

${GENERATED_HEADER.replace("// ", "")}

This directory contains typed TypeScript wrappers for every MCP tool
available to CTO agents. Each server (e.g. \`github\`, \`linear\`) has
its own subdirectory with one file per tool.

## Available servers

${serverList}

## Usage

\`\`\`typescript
import { search_code } from "./servers/${example}/search_code.ts";

const results = await search_code({ q: "callTool", repo: "5dlabs/cto" });
console.log(results);
\`\`\`

Or import everything from a server:

\`\`\`typescript
import * as ${example} from "./servers/${example}/index.ts";

await ${example}.search_code({ q: "callTool" });
\`\`\`

## How this was generated

The \`codegen.ts\` script fetches the tool catalog from the MCP server
via \`tools/list\` and writes typed wrappers. It runs at agent pod startup.

Re-run with:

\`\`\`bash
deno task codegen
\`\`\`

## Runtime

All tool functions call through \`mcp.ts\` which handles JSON-RPC transport,
routing (local sidecar vs. remote), and retries.
`;
}

// ─── MCP catalog fetch ──────────────────────────────────────────────────────

async function fetchToolCatalog(): Promise<ToolDef[]> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (AGENT_ID) headers["X-Agent-Id"] = AGENT_ID;
  if (AGENT_PREWARM) headers["X-Agent-Prewarm"] = AGENT_PREWARM;

  const body = JSON.stringify({
    jsonrpc: "2.0",
    id: 1,
    method: "tools/list",
  });

  for (let attempt = 1; attempt <= RETRY_COUNT; attempt++) {
    try {
      console.log(`  Attempt ${attempt}/${RETRY_COUNT}: ${TOOLS_SERVER_URL}`);
      const res = await fetch(TOOLS_SERVER_URL, {
        method: "POST",
        headers,
        body,
      });

      if (!res.ok) {
        throw new Error(`HTTP ${res.status}: ${res.statusText}`);
      }

      const json: JsonRpcResponse<ToolsListResult> = await res.json();

      if (json.error) {
        throw new Error(`JSON-RPC error ${json.error.code}: ${json.error.message}`);
      }

      return json.result?.tools ?? [];
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  ✗ Attempt ${attempt} failed: ${msg}`);

      if (attempt < RETRY_COUNT) {
        console.log(`  Retrying in ${RETRY_DELAY_MS / 1000}s...`);
        await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
      }
    }
  }

  throw new Error(
    `Failed to fetch tool catalog after ${RETRY_COUNT} attempts from ${TOOLS_SERVER_URL}`,
  );
}

// ─── Local stdio server discovery ────────────────────────────────────────────

interface StdioJsonRpcResponse<T = unknown> {
  jsonrpc: "2.0";
  id?: number;
  result?: T;
  error?: { code: number; message: string; data?: unknown };
}

/**
 * Read one newline-delimited JSON-RPC response matching `id` from a reader.
 * Skips notifications (no id) and non-JSON lines.
 */
async function readJsonRpcLine<T>(
  reader: ReadableStreamDefaultReader<string>,
  buffer: { value: string },
  expectedId: number,
): Promise<StdioJsonRpcResponse<T>> {
  for (;;) {
    const nlIdx = buffer.value.indexOf("\n");
    if (nlIdx !== -1) {
      const line = buffer.value.slice(0, nlIdx);
      buffer.value = buffer.value.slice(nlIdx + 1);
      if (line.trim().length === 0) continue;
      let msg: Record<string, unknown>;
      try {
        msg = JSON.parse(line);
      } catch {
        continue; // skip non-JSON lines (e.g. logging)
      }
      if (!("id" in msg)) continue; // skip notifications
      if (msg.id === expectedId) return msg as unknown as StdioJsonRpcResponse<T>;
      continue;
    }
    const { value, done } = await reader.read();
    if (done) throw new Error("Stdio stream closed before response received");
    buffer.value += value;
  }
}

/**
 * Discover tools from a single local stdio MCP server.
 * Spawns the process, performs the MCP handshake, calls tools/list,
 * then kills the process. Returns the raw tool list.
 */
async function discoverLocalServerTools(
  serverName: string,
  config: LocalServerConfig,
): Promise<ToolDef[]> {
  const cwd = config.workingDirectory ?? Deno.cwd();

  const childEnv: Record<string, string> = {};
  const parentPath = Deno.env.get("PATH");
  if (parentPath) childEnv["PATH"] = parentPath;
  childEnv["WORKING_DIRECTORY"] = cwd;
  childEnv["PROJECT_DIR"] = cwd;
  if (config.env) Object.assign(childEnv, config.env);

  const cmd = new Deno.Command(config.command, {
    args: config.args,
    cwd,
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
    env: childEnv,
  });

  const proc = cmd.spawn();

  // Drain stderr so the child process doesn't block
  proc.stderr.pipeTo(
    new WritableStream({ write() { /* discard */ } }),
  ).catch(() => { /* ignore */ });

  const stdinWriter = proc.stdin.getWriter();
  const decoder = new TextDecoderStream();
  const stdoutReader = proc.stdout.pipeThrough(decoder).getReader();
  const buffer = { value: "" };

  const encoder = new TextEncoder();
  const writeLine = async (msg: Record<string, unknown>) => {
    await stdinWriter.write(encoder.encode(JSON.stringify(msg) + "\n"));
  };

  try {
    // Step 1: initialize
    await writeLine({
      jsonrpc: "2.0",
      id: 1,
      method: "initialize",
      params: {
        protocolVersion: "2024-11-05",
        capabilities: {},
        clientInfo: { name: "cto-codegen", version: "1.0.0" },
      },
    });

    const initResp = await readJsonRpcLine(stdoutReader, buffer, 1);
    if (initResp.error) {
      throw new Error(`Initialize failed for '${serverName}': ${initResp.error.message}`);
    }

    // Step 2: notifications/initialized
    await writeLine({
      jsonrpc: "2.0",
      method: "notifications/initialized",
    });

    // Step 3: tools/list
    await writeLine({
      jsonrpc: "2.0",
      id: 2,
      method: "tools/list",
    });

    const listResp = await readJsonRpcLine<ToolsListResult>(stdoutReader, buffer, 2);
    if (listResp.error) {
      throw new Error(`tools/list failed for '${serverName}': ${listResp.error.message}`);
    }

    return listResp.result?.tools ?? [];
  } finally {
    try { proc.kill(); } catch { /* already dead */ }
  }
}

/**
 * Fetch tools from all local stdio servers defined in client-config.json.
 * Each server's tools are prefixed with the server key (e.g. "filesystem_read_file").
 * If `tools` filter is specified in config, only matching tools are included.
 * Servers that fail to start are skipped with a warning.
 */
async function fetchLocalToolCatalog(): Promise<ToolDef[]> {
  const clientConfig = loadClientConfig();
  if (!clientConfig || Object.keys(clientConfig.localServers).length === 0) {
    return [];
  }

  const allTools: ToolDef[] = [];

  for (const [serverName, config] of Object.entries(clientConfig.localServers)) {
    try {
      console.log(`  Discovering local server '${serverName}': ${config.command} ${config.args.join(" ")}`);

      const tools = await Promise.race([
        discoverLocalServerTools(serverName, config),
        new Promise<never>((_, reject) =>
          setTimeout(() => reject(new Error(`Timeout after ${LOCAL_DISCOVERY_TIMEOUT_MS / 1000}s`)), LOCAL_DISCOVERY_TIMEOUT_MS)
        ),
      ]);

      // Filter tools if the config specifies a subset
      const allowedSet = config.tools.length > 0 ? new Set(config.tools) : null;

      for (const tool of tools) {
        if (allowedSet && !allowedSet.has(tool.name)) continue;
        // Prefix with server key
        allTools.push({
          ...tool,
          name: `${serverName}_${tool.name}`,
        });
      }

      console.log(`  ✓ ${serverName}: ${tools.length} tools discovered` +
        (allowedSet ? `, ${allTools.filter(t => t.name.startsWith(serverName + "_")).length} after filtering` : ""));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`  ⚠ Skipping local server '${serverName}': ${msg}`);
    }
  }

  return allTools;
}

// ─── File I/O ────────────────────────────────────────────────────────────────

async function ensureDir(path: string): Promise<void> {
  try {
    await Deno.mkdir(path, { recursive: true });
  } catch (err) {
    if (!(err instanceof Deno.errors.AlreadyExists)) throw err;
  }
}

async function writeFile(path: string, content: string): Promise<void> {
  await Deno.writeTextFile(path, content);
}

async function copyFile(src: string, dest: string): Promise<void> {
  const content = await Deno.readTextFile(src);
  await Deno.writeTextFile(dest, content);
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log("Fetching tool catalog...");

  // Fetch remote and local catalogs concurrently; don't let one block the other
  const [remoteResult, localResult] = await Promise.allSettled([
    fetchToolCatalog(),
    fetchLocalToolCatalog(),
  ]);

  const remoteTools: ToolDef[] =
    remoteResult.status === "fulfilled" ? remoteResult.value : [];
  const localTools: ToolDef[] =
    localResult.status === "fulfilled" ? localResult.value : [];

  if (remoteResult.status === "rejected") {
    const msg = remoteResult.reason instanceof Error
      ? remoteResult.reason.message
      : String(remoteResult.reason);
    console.warn(`  ⚠ Remote catalog failed: ${msg}`);
  }
  if (localResult.status === "rejected") {
    const msg = localResult.reason instanceof Error
      ? localResult.reason.message
      : String(localResult.reason);
    console.warn(`  ⚠ Local catalog failed: ${msg}`);
  }

  // Merge: remote takes precedence on name conflicts
  const toolsByName = new Map<string, ToolDef>();
  for (const tool of localTools) {
    toolsByName.set(tool.name, tool);
  }
  for (const tool of remoteTools) {
    toolsByName.set(tool.name, tool); // overwrites local if same name
  }
  const tools = [...toolsByName.values()];

  if (tools.length === 0) {
    console.error("No tools discovered from any source. Aborting.");
    Deno.exit(1);
  }

  // Parse and group by server prefix
  const parsed = tools.map(parseTool);
  const byServer = new Map<string, ParsedTool[]>();

  for (const tool of parsed) {
    const group = byServer.get(tool.serverPrefix) ?? [];
    group.push(tool);
    byServer.set(tool.serverPrefix, group);
  }

  const serverCount = byServer.size;
  console.log(
    `Generating ${parsed.length} tools across ${serverCount} servers ` +
    `(${remoteTools.length} remote, ${localTools.length} local)...`,
  );

  // Create output directories
  const serversDir = `${OUTPUT_DIR}/servers`;
  await ensureDir(serversDir);

  // Generate tool files per server
  for (const [prefix, serverTools] of byServer) {
    const serverDir = `${serversDir}/${prefix}`;
    await ensureDir(serverDir);

    const funcNames: string[] = [];

    for (const tool of serverTools) {
      const content = generateToolFile(tool);
      await writeFile(`${serverDir}/${tool.funcName}.ts`, content);
      funcNames.push(tool.funcName);
    }

    // Generate server index.ts
    const indexContent = generateServerIndex(funcNames);
    await writeFile(`${serverDir}/index.ts`, indexContent);
  }

  // Copy mcp.ts from source directory to output
  const scriptDir = new URL(".", import.meta.url).pathname.replace(/\/$/, "");
  const mcpSrc = `${scriptDir}/mcp.ts`;
  try {
    await copyFile(mcpSrc, `${OUTPUT_DIR}/mcp.ts`);
    console.log("  Copied mcp.ts");
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`  ⚠ Could not copy mcp.ts: ${msg}`);
    console.warn("    Agents will need to ensure mcp.ts is present at runtime.");
  }

  // Generate deno.json
  await writeFile(`${OUTPUT_DIR}/deno.json`, generateDenoJson());

  // Generate README.md
  const serverNames = [...byServer.keys()];
  await writeFile(`${OUTPUT_DIR}/README.md`, generateReadme(serverNames));

  console.log(
    `Done. Output at ${OUTPUT_DIR} — ` +
    `${remoteTools.length} remote + ${localTools.length} local = ${tools.length} total tools`,
  );
}

if (import.meta.main) {
  main();
}
