{{- if .Values.tenant.id }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant-agents.fullname" . }}
  namespace: {{ .Values.tenant.namespace | default .Release.Namespace }}
  labels:
    {{- include "tenant-agents.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
