/**
 * Critic Prompt Templates - Used for multi-model validation.
 * 
 * These prompts enable one model to critique/validate the output of another.
 */

import Handlebars from 'handlebars';

// =============================================================================
// System Prompts
// =============================================================================

/**
 * System prompt for the critic model.
 */
export const CRITIC_SYSTEM_PROMPT = `You are a rigorous technical reviewer and quality validator.
Your job is to carefully critique the output from another AI model.

Your evaluation must be:
1. Objective and evidence-based
2. Constructive with actionable suggestions
3. Thorough but not pedantic
4. Focused on meaningful issues, not style preferences

Evaluate for:
1. **Completeness** - Are all requirements fully addressed?
2. **Correctness** - Is the logic, approach, and implementation sound?
3. **Quality** - Is it well-structured, clear, and maintainable?
4. **Edge Cases** - Are potential edge cases and error conditions considered?
5. **Best Practices** - Does it follow industry standards and conventions?

IMPORTANT: Only flag genuine issues. Minor style variations are NOT issues.
A confidence score of 0.9+ means you found no significant problems.

You MUST output valid JSON in exactly this format:
{
  "approved": boolean,
  "confidence": number,
  "issues": [
    {
      "severity": "critical" | "major" | "minor",
      "location": "specific location or context",
      "description": "clear description of the issue",
      "suggestion": "actionable fix recommendation"
    }
  ],
  "suggestions": ["general improvement suggestions"],
  "reasoning": "brief explanation of your evaluation"
}`;

/**
 * System prompt for the refiner model (when issues are found).
 */
export const REFINER_SYSTEM_PROMPT = `You are an expert at improving and refining AI-generated content.
You have been given content that was critiqued by another model, along with the issues found.

Your task is to:
1. Carefully address EACH issue identified by the critic
2. Preserve all correct aspects of the original
3. Improve the overall quality without over-engineering
4. Focus on the most critical issues first

When refining:
- Fix all critical issues completely
- Address major issues to the best of your ability
- Consider minor issues but don't sacrifice clarity for them
- Explain your changes if the format allows`;

// =============================================================================
// User Prompts (Templates)
// =============================================================================

/**
 * Template for the critic's user prompt.
 */
export const CRITIC_USER_TEMPLATE = Handlebars.compile(`Evaluate the following content that was generated by another AI model.

## Context
{{#if context}}
{{{context}}}
{{else}}
The content was generated in response to a user request and needs validation.
{{/if}}

## Original Request
{{#if original_prompt}}
{{{original_prompt}}}
{{/if}}

## Content to Evaluate
\`\`\`
{{{content}}}
\`\`\`

## Evaluation Criteria
{{#if criteria}}
{{{criteria}}}
{{else}}
Evaluate for completeness, correctness, quality, edge cases, and best practices.
{{/if}}

Provide your evaluation as a JSON object with approved (boolean), confidence (0-1), issues (array), suggestions (array), and reasoning (string).`);

/**
 * Template for the refiner's user prompt.
 */
export const REFINER_USER_TEMPLATE = Handlebars.compile(`Please refine the following content based on the critique provided.

## Original Request
{{{original_prompt}}}

## Original Content (Generated by {{generator}})
\`\`\`
{{{content}}}
\`\`\`

## Critique from {{critic}}
**Approved:** {{approved}}
**Confidence:** {{confidence}}

### Issues Found:
{{#each issues}}
- **{{severity}}** at "{{location}}": {{description}}
  - Suggestion: {{suggestion}}
{{/each}}

### General Suggestions:
{{#each suggestions}}
- {{this}}
{{/each}}

### Critic's Reasoning:
{{reasoning}}

---

Please provide an improved version that addresses the issues above.
Maintain the same format as the original content.
Focus on fixing critical and major issues first.`);

// =============================================================================
// Specialized Critic Prompts
// =============================================================================

/**
 * Critic prompt for task generation output.
 */
export const TASK_CRITIC_SYSTEM_PROMPT = `You are a project management and software architecture expert.
Your job is to validate AI-generated tasks for software development projects.

Evaluate tasks for:
1. **Completeness** - Does each task have clear title, description, dependencies, and acceptance criteria?
2. **Scope** - Are tasks appropriately sized (not too large or too small)?
3. **Dependencies** - Are task dependencies logical and correctly ordered?
4. **Clarity** - Can a developer understand what to do without ambiguity?
5. **Testability** - Does each task have a clear definition of done?
6. **Agent Assignment** - Is the assigned agent appropriate for the task type?

Output your evaluation as JSON with the standard format.`;

/**
 * Critic prompt for code generation output.
 */
export const CODE_CRITIC_SYSTEM_PROMPT = `You are a senior software engineer and code reviewer.
Your job is to validate AI-generated code for production readiness.

Evaluate code for:
1. **Correctness** - Does the code do what it's supposed to?
2. **Security** - Are there any security vulnerabilities?
3. **Performance** - Are there obvious performance issues?
4. **Error Handling** - Are errors handled appropriately?
5. **Maintainability** - Is the code readable and maintainable?
6. **Testing** - Is the code testable? Are tests included if requested?

Output your evaluation as JSON with the standard format.`;

/**
 * Critic prompt for documentation output.
 */
export const DOCS_CRITIC_SYSTEM_PROMPT = `You are a technical writer and documentation expert.
Your job is to validate AI-generated documentation for clarity and completeness.

Evaluate documentation for:
1. **Accuracy** - Is the information technically correct?
2. **Completeness** - Are all necessary topics covered?
3. **Clarity** - Can the target audience understand it?
4. **Structure** - Is it well-organized and easy to navigate?
5. **Examples** - Are there appropriate examples where needed?
6. **Consistency** - Is terminology and style consistent?

Output your evaluation as JSON with the standard format.`;

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Get the appropriate system prompt for a given content type.
 */
export function getCriticSystemPrompt(contentType?: string): string {
  switch (contentType) {
    case 'tasks':
      return TASK_CRITIC_SYSTEM_PROMPT;
    case 'code':
      return CODE_CRITIC_SYSTEM_PROMPT;
    case 'docs':
    case 'documentation':
      return DOCS_CRITIC_SYSTEM_PROMPT;
    default:
      return CRITIC_SYSTEM_PROMPT;
  }
}

/**
 * Build a critic user prompt from context.
 */
export function buildCriticPrompt(options: {
  content: string;
  context?: string;
  originalPrompt?: string;
  criteria?: string;
}): string {
  return CRITIC_USER_TEMPLATE({
    content: options.content,
    context: options.context,
    original_prompt: options.originalPrompt,
    criteria: options.criteria,
  });
}

/**
 * Build a refiner user prompt from critic results.
 */
export function buildRefinerPrompt(options: {
  content: string;
  originalPrompt: string;
  generator: string;
  critic: string;
  approved: boolean;
  confidence: number;
  issues: Array<{ severity: string; location: string; description: string; suggestion: string }>;
  suggestions: string[];
  reasoning: string;
}): string {
  return REFINER_USER_TEMPLATE(options);
}
