/**
 * Generate Prompts operation - creates folder structure with prompt files.
 * 
 * Generates:
 * - .tasks/docs/task-{id}/prompt.md
 * - .tasks/docs/task-{id}/prompt.xml
 * - .tasks/docs/task-{id}/acceptance.md
 * - .tasks/docs/task-{id}/subtasks/task-{id}.{subtask_id}/...
 */

import type { GeneratedTask, GeneratedSubtask, AgentResponse, DecisionPoint } from './types';
import * as fs from 'fs';
import * as path from 'path';

const logger = { info: (...args: unknown[]) => console.error(...args), debug: (...args: unknown[]) => console.error(...args), error: (...args: unknown[]) => console.error(...args) };

export interface GeneratePromptsPayload {
  /** Tasks to generate prompts for */
  tasks: GeneratedTask[];
  /** Output directory (default: .tasks/docs) */
  output_dir?: string;
  /** Project name */
  project_name?: string;
  /** Include subtasks */
  include_subtasks?: boolean;
}

export interface GeneratePromptsData {
  /** Number of task folders created */
  task_count: number;
  /** Number of subtask folders created */
  subtask_count: number;
  /** Total files generated */
  file_count: number;
  /** List of generated files */
  files: string[];
}

/**
 * Map agent hint from title to agent name.
 */
function extractAgent(title: string): { agent: string; stack: string } {
  const match = title.match(/\((\w+)\s*-\s*([^)]+)\)/);
  if (match) {
    return { agent: match[1].toLowerCase(), stack: match[2] };
  }
  return { agent: 'unknown', stack: 'unknown' };
}

/**
 * Generate markdown prompt for a task.
 */
function generateTaskPromptMd(task: GeneratedTask, projectName: string): string {
  const { agent, stack } = extractAgent(task.title);
  const cleanTitle = task.title.replace(/\s*\([^)]+\)\s*$/, '').trim();
  
  return `# Task ${task.id}: ${cleanTitle}

## Agent
- **Name**: ${agent.charAt(0).toUpperCase() + agent.slice(1)}
- **Stack**: ${stack}

## Overview
${task.description}

## Priority
${task.priority || 'medium'}

## Dependencies
${task.dependencies.length > 0 ? task.dependencies.map(d => `- Task ${d}`).join('\n') : 'None'}

## Implementation Details
${task.details || 'See acceptance criteria.'}

## Decision Points
${formatDecisionPoints(task.decision_points || task.decisionPoints)}

## Acceptance Criteria
${task.test_strategy || task.testStrategy || 'To be defined.'}

---
*Project: ${projectName}*
*Generated by intake-agent*
`;
}

/**
 * Generate XML prompt for a task.
 */
function generateTaskPromptXml(task: GeneratedTask, projectName: string): string {
  const { agent, stack } = extractAgent(task.title);
  const cleanTitle = task.title.replace(/\s*\([^)]+\)\s*$/, '').trim();
  
  return `<?xml version="1.0" encoding="UTF-8"?>
<task id="${task.id}" project="${projectName}">
  <title>${escapeXml(cleanTitle)}</title>
  <agent name="${agent}" stack="${escapeXml(stack)}" />
  <priority>${task.priority || 'medium'}</priority>
  <status>${task.status || 'pending'}</status>
  
  <description>
    ${escapeXml(task.description)}
  </description>
  
  <dependencies>
    ${task.dependencies.map(d => `<dependency task_id="${d}" />`).join('\n    ')}
  </dependencies>
  
  <implementation>
    <details>${escapeXml(task.details || '')}</details>
  </implementation>
  
  <decision_points>
    ${formatDecisionPointsXml(task.decision_points || task.decisionPoints)}
  </decision_points>
  
  <acceptance_criteria>
    ${escapeXml(task.test_strategy || task.testStrategy || '')}
  </acceptance_criteria>
</task>
`;
}

/**
 * Generate acceptance criteria markdown.
 */
function generateAcceptanceMd(task: GeneratedTask): string {
  const criteria = task.test_strategy || task.testStrategy || '';
  const criteriaList = criteria.split(/[,;]/).map(c => c.trim()).filter(c => c);
  
  return `# Acceptance Criteria - Task ${task.id}

## Task
${task.title}

## Criteria
${criteriaList.length > 0 
    ? criteriaList.map((c, i) => `${i + 1}. ${c}`).join('\n')
    : '- To be defined'}

## Decision Points Requiring Resolution
${formatDecisionPointsForAcceptance(task.decision_points || task.decisionPoints)}

## Definition of Done
- [ ] All acceptance criteria met
- [ ] Tests passing
- [ ] Code reviewed
- [ ] Documentation updated
${((task.decision_points || task.decisionPoints) || []).filter(d => d.requires_approval || d.requiresApproval).map(d => 
    `- [ ] Decision "${d.id}" approved: ${d.description}`
  ).join('\n')}
`;
}

/**
 * Format decision points for markdown.
 */
function formatDecisionPoints(points?: DecisionPoint[]): string {
  if (!points || points.length === 0) return 'None';
  
  return points.map(p => {
    const approval = (p.requires_approval || p.requiresApproval) ? '⚠️ **Requires Approval**' : '';
    const constraint = p.constraint_type || p.constraintType || 'open';
    return `### ${p.id}: ${p.description}
- **Category**: ${p.category}
- **Constraint**: ${constraint}
- **Options**: ${p.options.join(', ')}
${approval}`;
  }).join('\n\n');
}

/**
 * Format decision points for XML.
 */
function formatDecisionPointsXml(points?: DecisionPoint[]): string {
  if (!points || points.length === 0) return '';
  
  return points.map(p => {
    const constraint = p.constraint_type || p.constraintType || 'open';
    const approval = p.requires_approval || p.requiresApproval || false;
    return `<decision id="${p.id}" category="${p.category}" constraint="${constraint}" requires_approval="${approval}">
      <description>${escapeXml(p.description)}</description>
      <options>
        ${p.options.map(o => `<option>${escapeXml(o)}</option>`).join('\n        ')}
      </options>
    </decision>`;
  }).join('\n    ');
}

/**
 * Format decision points for acceptance criteria.
 */
function formatDecisionPointsForAcceptance(points?: DecisionPoint[]): string {
  if (!points || points.length === 0) return 'None';
  
  const hardConstraints = points.filter(p => (p.constraint_type || p.constraintType) === 'hard');
  const approvalRequired = points.filter(p => p.requires_approval || p.requiresApproval);
  
  let result = '';
  
  if (hardConstraints.length > 0) {
    result += '### Hard Constraints (Must Follow)\n';
    result += hardConstraints.map(p => `- **${p.id}**: ${p.description}`).join('\n');
    result += '\n\n';
  }
  
  if (approvalRequired.length > 0) {
    result += '### Requires Human Approval\n';
    result += approvalRequired.map(p => `- **${p.id}**: ${p.description} (${p.category})`).join('\n');
  }
  
  return result || 'All decisions can be made by the agent.';
}

/**
 * Escape XML special characters.
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Generate subtask prompt files.
 */
function generateSubtaskPromptMd(subtask: GeneratedSubtask, parentTaskId: number, projectName: string): string {
  return `# Subtask ${parentTaskId}.${subtask.id}: ${subtask.title}

## Parent Task
Task ${parentTaskId}

## Subagent Type
${subtask.subagent_type || subtask.subagentType || 'implementer'}

## Parallelizable
${subtask.parallelizable ? 'Yes - can run concurrently' : 'No - must wait for dependencies'}

## Description
${subtask.description}

## Dependencies
${subtask.dependencies.length > 0 ? subtask.dependencies.map(d => `- Subtask ${parentTaskId}.${d}`).join('\n') : 'None'}

## Implementation Details
${subtask.details || 'See parent task.'}

## Test Strategy
${subtask.test_strategy || subtask.testStrategy || 'See parent task acceptance criteria.'}

---
*Project: ${projectName}*
`;
}

/**
 * Generate prompts for all tasks.
 */
export async function generatePrompts(
  payload: GeneratePromptsPayload
): Promise<AgentResponse<GeneratePromptsData>> {
  const outputDir = payload.output_dir || '.tasks/docs';
  const projectName = payload.project_name || 'project';
  const tasks = payload.tasks;
  const includeSubtasks = payload.include_subtasks !== false;
  
  logger.info('Generating prompts', { 
    taskCount: tasks.length, 
    outputDir, 
    includeSubtasks 
  });
  
  const files: string[] = [];
  let subtaskCount = 0;
  
  try {
    for (const task of tasks) {
      const taskDir = path.join(outputDir, `task-${task.id}`);
      
      // Create task directory
      fs.mkdirSync(taskDir, { recursive: true });
      
      // Generate prompt.md
      const promptMd = generateTaskPromptMd(task, projectName);
      const promptMdPath = path.join(taskDir, 'prompt.md');
      fs.writeFileSync(promptMdPath, promptMd);
      files.push(promptMdPath);
      
      // Generate prompt.xml
      const promptXml = generateTaskPromptXml(task, projectName);
      const promptXmlPath = path.join(taskDir, 'prompt.xml');
      fs.writeFileSync(promptXmlPath, promptXml);
      files.push(promptXmlPath);
      
      // Generate acceptance.md
      const acceptanceMd = generateAcceptanceMd(task);
      const acceptancePath = path.join(taskDir, 'acceptance.md');
      fs.writeFileSync(acceptancePath, acceptanceMd);
      files.push(acceptancePath);
      
      logger.debug(`Generated task-${task.id}`, { files: 3 });
      
      // Generate subtask prompts if available
      if (includeSubtasks && task.subtasks && task.subtasks.length > 0) {
        const subtasksDir = path.join(taskDir, 'subtasks');
        fs.mkdirSync(subtasksDir, { recursive: true });
        
        for (const subtask of task.subtasks) {
          const subtaskDir = path.join(subtasksDir, `task-${task.id}.${subtask.id}`);
          fs.mkdirSync(subtaskDir, { recursive: true });
          
          const subtaskMd = generateSubtaskPromptMd(subtask, task.id, projectName);
          const subtaskPath = path.join(subtaskDir, 'prompt.md');
          fs.writeFileSync(subtaskPath, subtaskMd);
          files.push(subtaskPath);
          
          subtaskCount++;
        }
      }
    }
    
    logger.info('Prompt generation complete', { 
      taskCount: tasks.length, 
      subtaskCount, 
      fileCount: files.length 
    });
    
    return {
      success: true,
      data: {
        task_count: tasks.length,
        subtask_count: subtaskCount,
        file_count: files.length,
        files,
      },
      usage: { input_tokens: 0, output_tokens: 0, total_tokens: 0 },
      model: 'none',
      provider: 'intake-agent',
    };
  } catch (e) {
    const error = e instanceof Error ? e.message : 'Unknown error';
    logger.error('Prompt generation failed', { error });
    return {
      success: false,
      error: `Failed to generate prompts: ${error}`,
      error_type: 'file_error',
    };
  }
}
