---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data
  namespace: messaging
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: message-bus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor
  resources:
    requests:
      storage: 10Gi
