#!/bin/bash
set -euo pipefail

# Script to generate multiple templates ConfigMaps split by type
# This solves both the ArgoCD .Files issue and the 1MB ConfigMap size limit
#
# Directory structure (as of restructuring):
#   templates/
#   ├── _shared/          - Shared partials (header, config, etc.)
#   ├── agents/           - Agent-specific templates
#   │   ├── morgan/intake/
#   │   ├── atlas/intake/
#   │   ├── rex/coder/
#   │   └── ...
#   └── clis/             - CLI invocation templates
#       ├── claude/
#       ├── cursor/
#       └── ...

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$CHART_DIR/templates"

# Support specifying templates path (for repo root templates)
TEMPLATES_PATH="${TEMPLATES_PATH:-$CHART_DIR/../../..}/templates"

cd "$(dirname "$TEMPLATES_PATH")"
TEMPLATES_PATH="$(basename "$TEMPLATES_PATH")"

echo "Generating split ConfigMaps from agent templates..."
echo "  Templates path: $(pwd)/$TEMPLATES_PATH"

# Verify templates directory exists
if [ ! -d "$TEMPLATES_PATH" ]; then
  echo "❌ Templates directory not found: $TEMPLATES_PATH"
  exit 1
fi

# Define ConfigMap types
CLI_TYPES=("claude" "cursor" "codex" "opencode" "gemini" "factory")
AGENT_TYPES=("intake" "healer" "integration" "watch")

generate_configmap() {
  local name=$1
  local output_file="$OUTPUT_DIR/templates-${name}.yaml"
  
  echo ""
  echo "Generating ConfigMap: $name"
  
  # Header with metadata
  cat > "$output_file" << HEADER_EOF
# This file is auto-generated by scripts/generate-agent-templates-configmaps-split.sh
# DO NOT EDIT MANUALLY - edit the source files in templates/ instead
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "controller.fullname" . }}-templates-${name}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: templates
    templates/type: ${name}
  annotations:
    templates-checksum: "CHECKSUM_PLACEHOLDER"
binaryData:
HEADER_EOF

  local files_list=""
  
  case "$name" in
    shared)
      # Shared partials from _shared/
      files_list=$(find -L "$TEMPLATES_PATH/_shared" -type f \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      ;;
    intake)
      # All intake templates from agents/*/intake/ AND templates/intake/
      files_list=$(find -L "$TEMPLATES_PATH/agents" -type f -path "*/intake/*" \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      # Also include templates/intake/ directory (standalone intake scripts)
      intake_standalone=$(find -L "$TEMPLATES_PATH/intake" -type f \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      if [ -n "$intake_standalone" ]; then
        files_list+=$'\n'"$intake_standalone"
      fi
      ;;
    healer)
      # All healer templates from agents/*/healer/
      files_list=$(find -L "$TEMPLATES_PATH/agents" -type f -path "*/healer/*" \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      ;;
    integration)
      # Integration templates from agents/*/integration/
      files_list=$(find -L "$TEMPLATES_PATH/agents" -type f -path "*/integration/*" \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      ;;
    watch)
      # Watch templates from agents/*/watch/ (if any)
      files_list=$(find -L "$TEMPLATES_PATH/agents" -type f -path "*/watch/*" \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      ;;
    claude|cursor|codex|opencode|gemini|factory)
      # CLI-specific templates from clis/<cli>/
      files_list=$(find -L "$TEMPLATES_PATH/clis/$name" -type f \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      # Also include all agent coder/docs templates (they use CLI partials)
      agent_code=$(find -L "$TEMPLATES_PATH/agents" -type f \( -path "*/coder/*" -o -path "*/docs/*" -o -path "*/test/*" -o -path "*/quality/*" -o -path "*/security/*" -o -path "*/deploy/*" -o -path "*/review/*" -o -path "*/pm/*" \) \( -name "*.hbs" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | LC_ALL=C sort || true)
      if [ -n "$agent_code" ]; then
        files_list+=$'\n'"$agent_code"
      fi
      ;;
    *)
      echo "  ⚠️  Unknown ConfigMap type: $name"
      rm "$output_file"
      return
      ;;
  esac
  
  # Remove duplicates and empty lines
  files_list=$(echo "$files_list" | LC_ALL=C sort -u | grep -v '^$' || true)
  
  if [ -z "$files_list" ]; then
    echo "  ⚠️  No files found for $name"
    rm "$output_file"
    return
  fi
  
  # Compute checksum
  checksum_tmp=$(mktemp)
  trap 'rm -f "$checksum_tmp"' EXIT
  
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    printf '%s\n' "$f" >> "$checksum_tmp"
    cat "$f" >> "$checksum_tmp"
    printf '\n' >> "$checksum_tmp"
  done <<< "$files_list"
  
  if command -v shasum >/dev/null 2>&1; then
    local checksum=$(shasum -a 256 "$checksum_tmp" | awk '{print $1}')
  else
    local checksum=$(openssl dgst -sha256 -r "$checksum_tmp" | awk '{print $1}')
  fi
  
  # Inject checksum (portable sed for both macOS and Linux)
  if sed --version 2>&1 | grep -q GNU; then
    sed -i "s/CHECKSUM_PLACEHOLDER/${checksum}/" "$output_file"
  else
    sed -i '' "s/CHECKSUM_PLACEHOLDER/${checksum}/" "$output_file"
  fi
  
  # Add files to ConfigMap
  local file_count=0
  while IFS= read -r file; do
    [ -z "$file" ] && continue
    
    # Convert path to ConfigMap key (remove templates/ prefix)
    key=$(echo "$file" | sed "s|$TEMPLATES_PATH/||" | sed 's|/|_|g')
    
    echo "    Processing: $file -> $key"
    
    # Base64 encode
    encoded=$(base64 < "$file" | tr -d '\n')
    
    # Add to ConfigMap
    echo "  $key: $encoded" >> "$output_file"
    file_count=$((file_count + 1))
  done <<< "$files_list"
  
  local size=$(wc -c < "$output_file")
  echo "  ✓ Generated: $output_file"
  echo "  ✓ Checksum: $checksum"
  echo "  ✓ Files: $file_count"
  echo "  ✓ Size: $size bytes ($(numfmt --to=iec-i --suffix=B $size 2>/dev/null || echo "$size bytes"))"
  
  if [ $size -gt 1048576 ]; then
    echo "  ❌ ERROR: ConfigMap exceeds 1MB limit!"
    return 1
  fi
}

# Generate shared resources ConfigMap
generate_configmap "shared"

# Generate intake ConfigMap (Morgan, Atlas intake)
generate_configmap "intake"

# Generate healer ConfigMap  
generate_configmap "healer"

# Generate integration ConfigMap
generate_configmap "integration"

# Generate CLI-specific ConfigMaps
for cli in "${CLI_TYPES[@]}"; do
  generate_configmap "$cli"
done

echo ""
echo "✅ All ConfigMaps generated successfully!"
echo ""
echo "Generated files:"
ls -lh "$OUTPUT_DIR"/templates-*.yaml 2>/dev/null || echo "No files generated"
echo ""
echo "Next steps:"
echo "1. Review the generated files"
echo "2. Commit changes and deploy to Kind"
