#!/bin/bash
set -euo pipefail

# Generate Blaze scripts ConfigMap with base64-encoded script files

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(cd "$CHART_DIR/../../.." && pwd)"
OUTPUT_FILE="$CHART_DIR/templates/agent-scripts-blaze.yaml"

echo "Generating Blaze scripts ConfigMap..."
echo "Repo root: $REPO_ROOT"
echo "Scripts source: $REPO_ROOT/scripts/blaze"
echo "Output: $OUTPUT_FILE"

# Check if scripts exist
if [ ! -d "$REPO_ROOT/scripts/blaze" ]; then
  echo "❌ Error: Blaze scripts directory not found at $REPO_ROOT/scripts/blaze"
  exit 1
fi

# Header
cat > "$OUTPUT_FILE" << 'EOF'
# ConfigMap containing Blaze frontend agent scripts
# This file is auto-generated by scripts/generate-blaze-scripts-configmap.sh
# DO NOT EDIT MANUALLY - edit the source files in scripts/blaze/ instead
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "controller.fullname" . }}-agent-scripts-blaze
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-scripts
    agent-scripts/type: blaze
binaryData:
EOF

# Encode each script
for script in init-nextjs-project.sh deploy-to-k8s.sh setup-ngrok-ingress.sh run-playwright-tests.sh; do
  script_path="$REPO_ROOT/scripts/blaze/$script"
  if [ ! -f "$script_path" ]; then
    echo "⚠️  Warning: Script not found: $script_path"
    continue
  fi
  
  echo "  Encoding: $script"
  encoded=$(base64 < "$script_path" | tr -d '\n')
  echo "  $script: $encoded" >> "$OUTPUT_FILE"
done

echo ""
echo "✅ Blaze scripts ConfigMap generated successfully!"
echo "   Output: $OUTPUT_FILE"
echo "   Size: $(wc -c < "$OUTPUT_FILE") bytes"

