#!/bin/bash
set -euo pipefail

# Generate Spark scripts ConfigMap with base64-encoded script files

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(cd "$CHART_DIR/../../.." && pwd)"
OUTPUT_FILE="$CHART_DIR/templates/agent-scripts-spark.yaml"

echo "Generating Spark scripts ConfigMap..."
echo "Repo root: $REPO_ROOT"
echo "Scripts source: $REPO_ROOT/scripts/spark"
echo "Output: $OUTPUT_FILE"

# Check if scripts exist
if [ ! -d "$REPO_ROOT/scripts/spark" ]; then
  echo "❌ Error: Spark scripts directory not found at $REPO_ROOT/scripts/spark"
  exit 1
fi

# Header
cat > "$OUTPUT_FILE" << 'EOF'
# ConfigMap containing Spark mobile agent scripts
# This file is auto-generated by scripts/generate-spark-scripts-configmap.sh
# DO NOT EDIT MANUALLY - edit the source files in scripts/spark/ instead
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "controller.fullname" . }}-agent-scripts-spark
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-scripts
    agent-scripts/type: spark
binaryData:
EOF

# Encode each script
for script in init-expo-project.sh init-bare-rn-project.sh setup-eas-build.sh run-detox-tests.sh; do
  script_path="$REPO_ROOT/scripts/spark/$script"
  if [ ! -f "$script_path" ]; then
    echo "⚠️  Warning: Script not found: $script_path"
    continue
  fi
  
  echo "  Encoding: $script"
  encoded=$(base64 < "$script_path" | tr -d '\n')
  echo "  $script: $encoded" >> "$OUTPUT_FILE"
done

echo ""
echo "✅ Spark scripts ConfigMap generated successfully!"
echo "   Output: $OUTPUT_FILE"
echo "   Size: $(wc -c < "$OUTPUT_FILE") bytes"
