apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-gateway.fullname" . }}-config
  labels:
    {{- include "hermes-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl .Values.configYaml . | nindent 4 }}
  SOUL.md: |
    {{- tpl .Values.instructionFiles.soulMd . | nindent 4 }}
  AGENTS.md: |
    {{- tpl .Values.instructionFiles.agentsMd . | nindent 4 }}
  TOOLS.md: |
    {{- tpl .Values.instructionFiles.toolsMd . | nindent 4 }}
