#!/usr/bin/env bash
# =============================================================================
# Credential Setup Script for CLI Integration Tests
# =============================================================================
#
# Auto-discovers credentials from 1Password and Kubernetes and writes to .env.
# Linear runtime tokens come from PM/Kubernetes; 1Password is only used for
# client credentials and other long-lived secrets.
# Supports multiple agents: Morgan, Bolt, Blaze, etc.
#
# Usage:
#   ./scripts/setup-credentials.sh [agent]
#
# Examples:
#   ./scripts/setup-credentials.sh          # Default: bolt
#   ./scripts/setup-credentials.sh bolt     # Bolt agent
#   ./scripts/setup-credentials.sh rex      # Rex/Morgan agent
#
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

AGENT="${1:-bolt}"

echo "=== Credential Setup for ${AGENT} ===" >&2

# Check 1Password CLI
if ! command -v op &> /dev/null; then
  echo "❌ 1Password CLI (op) not found. Please install it first." >&2
  exit 1
fi

# Check if signed in
if ! op account list &> /dev/null; then
  echo "❌ Not signed into 1Password. Run: eval \$(op signin)" >&2
  exit 1
fi

echo "✓ 1Password CLI ready" >&2

# -----------------------------------------------------------------------------
# Linear runtime token (minted by PM, stored in Kubernetes)
# -----------------------------------------------------------------------------
echo "" >&2
echo "--- Fetching Linear runtime token from PM/Kubernetes ---" >&2

PM_BASE_URL="${PM_BASE_URL:-https://pm.5dlabs.ai}"
NAMESPACE="${NAMESPACE:-cto}"

case "$AGENT" in
  rex|morgan) LINEAR_AGENT_NAME="morgan" ;;
  *)          LINEAR_AGENT_NAME="$AGENT" ;;
esac

curl -fsS -X POST "${PM_BASE_URL}/oauth/mint/${LINEAR_AGENT_NAME}" >/dev/null 2>&1 || true

LINEAR_OAUTH_TOKEN=$(kubectl get secret "linear-app-${LINEAR_AGENT_NAME}" -n "${NAMESPACE}" \
  -o jsonpath='{.data.access_token}' 2>/dev/null | base64 -d 2>/dev/null || echo "")

if [ -z "$LINEAR_OAUTH_TOKEN" ]; then
  echo "❌ Failed to fetch Linear runtime token for ${LINEAR_AGENT_NAME}" >&2
  exit 1
fi

echo "✓ Linear runtime token retrieved for ${LINEAR_AGENT_NAME}" >&2

# -----------------------------------------------------------------------------
# Anthropic API Key
# -----------------------------------------------------------------------------
echo "" >&2
echo "--- Fetching Anthropic API key ---" >&2

# Use item ID to avoid ambiguity (two items with same name)
ANTHROPIC_API_KEY=$(op read "op://Automation/2lljrd76lwjqcc6f5zogubj3zm/credential" 2>/dev/null) || {
  ANTHROPIC_API_KEY=$(op read "op://Automation/Anthropic API Key/credential" 2>/dev/null) || {
    echo "⚠ Could not fetch Anthropic API key - tests may fail" >&2
    ANTHROPIC_API_KEY=""
  }
}
[ -n "$ANTHROPIC_API_KEY" ] && echo "✓ Anthropic API key retrieved" >&2

# -----------------------------------------------------------------------------
# GitHub Credentials (agent-specific)
# -----------------------------------------------------------------------------
echo "" >&2
echo "--- Fetching GitHub credentials for ${AGENT} ---" >&2

case "$AGENT" in
  bolt)
    GITHUB_APP_NAME="GitHub-App-Bolt"
    ;;
  rex|morgan)
    GITHUB_APP_NAME="GitHub-App-Morgan"
    ;;
  blaze)
    GITHUB_APP_NAME="GitHub-App-Blaze"
    ;;
  *)
    echo "⚠ Unknown agent: ${AGENT}, skipping GitHub credentials" >&2
    GITHUB_APP_NAME=""
    ;;
esac

if [ -n "$GITHUB_APP_NAME" ]; then
  # GitHub Apps use app-id + private-key for authentication (not a simple token)
  GITHUB_APP_ID=$(op read "op://Automation/${GITHUB_APP_NAME}/app-id" 2>/dev/null) || {
    echo "⚠ Could not fetch GitHub App ID" >&2
    GITHUB_APP_ID=""
  }
  
  GITHUB_CLIENT_ID=$(op read "op://Automation/${GITHUB_APP_NAME}/client-id" 2>/dev/null) || {
    echo "⚠ Could not fetch GitHub Client ID" >&2
    GITHUB_CLIENT_ID=""
  }
  
  GITHUB_PRIVATE_KEY=$(op read "op://Automation/${GITHUB_APP_NAME}/private-key" 2>/dev/null) || {
    echo "⚠ Could not fetch GitHub private key" >&2
    GITHUB_PRIVATE_KEY=""
  }
  
  [ -n "$GITHUB_APP_ID" ] && echo "✓ GitHub App ID retrieved" >&2
  [ -n "$GITHUB_CLIENT_ID" ] && echo "✓ GitHub Client ID retrieved" >&2
  [ -n "$GITHUB_PRIVATE_KEY" ] && echo "✓ GitHub private key retrieved" >&2
  
  # Mark GitHub as available if we have the essential credentials
  [ -n "$GITHUB_APP_ID" ] && [ -n "$GITHUB_PRIVATE_KEY" ] && GITHUB_AVAILABLE="yes"
fi

# -----------------------------------------------------------------------------
# Write .env file
# -----------------------------------------------------------------------------
echo "" >&2
echo "--- Writing .env file ---" >&2

cat > "$ENV_FILE" << EOF
# =============================================================================
# CLI Integration Test Environment - Generated by setup-credentials.sh
# =============================================================================
# Agent: ${AGENT}
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

# Linear Integration
LINEAR_OAUTH_TOKEN=${LINEAR_OAUTH_TOKEN}
LINEAR_ISSUE_IDENTIFIER=\${LINEAR_ISSUE_IDENTIFIER:-CTOPA-2633}

# API Keys
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
EOF

# Add GitHub credentials if available
if [ -n "${GITHUB_APP_ID:-}" ]; then
  cat >> "$ENV_FILE" << EOF

# GitHub App Credentials (${GITHUB_APP_NAME})
GITHUB_APP_ID=${GITHUB_APP_ID}
EOF
fi

if [ -n "${GITHUB_CLIENT_ID:-}" ]; then
  echo "GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}" >> "$ENV_FILE"
fi

# Note: Private key is multi-line, handle carefully
if [ -n "${GITHUB_PRIVATE_KEY:-}" ]; then
  echo "" >> "$ENV_FILE"
  echo "# GitHub Private Key (base64 encoded for single line)" >> "$ENV_FILE"
  echo "GITHUB_PRIVATE_KEY_B64=$(echo "$GITHUB_PRIVATE_KEY" | base64 | tr -d '\n')" >> "$ENV_FILE"
fi

echo "✓ .env file written to ${ENV_FILE}" >&2

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo "" >&2
echo "=== Credential Setup Complete ===" >&2
echo "  Agent: ${AGENT}" >&2
echo "  Linear: ✓" >&2
echo "  Anthropic: $( [ -n "${ANTHROPIC_API_KEY:-}" ] && echo "✓" || echo "✗" )" >&2
echo "  GitHub: $( [ -n "${GITHUB_AVAILABLE:-}" ] && echo "✓" || echo "✗" )" >&2
echo "" >&2
echo "Next steps:" >&2
echo "  1. Set LINEAR_ISSUE_IDENTIFIER in .env (e.g., CTOPA-2634)" >&2
echo "  2. Run: ./setup.sh ${AGENT} coder" >&2
echo "  3. Run: docker compose up ${AGENT} ${AGENT}-sidecar" >&2
