#!/usr/bin/env bash
#
# extract-cluster-secrets.sh
#
# Extracts cluster-generated secrets and stores them in OpenBao.
# These are secrets that are generated by the cluster itself (not from 1Password)
# and need to be backed up to OpenBao for ExternalSecrets to sync.
#
# Secrets handled:
#   - mayastor: JWT token for etcd authentication
#   - seaweedfs-s3-credentials: S3 API credentials from SeaweedFS
#   - tailscale-auth: Pre-auth key from Headscale
#   - tools-kubernetes: Kubeconfig for MCP server
#
# Prerequisites:
#   - kubectl configured with cluster access
#   - OpenBao unsealed and accessible
#   - Port-forward to OpenBao: kubectl port-forward svc/openbao -n openbao 8200:8200
#
# Usage:
#   ./docs/scripts/extract-cluster-secrets.sh [--dry-run]
#

set -euo pipefail

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "🔍 Dry run mode - no changes will be made"
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters
SUCCESS_COUNT=0
SKIP_COUNT=0
FAIL_COUNT=0

echo "════════════════════════════════════════════════════════════════════════════"
echo "  Extract Cluster-Generated Secrets to OpenBao"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

# Check prerequisites
if ! command -v kubectl &> /dev/null; then
    echo -e "${RED}Error: kubectl not found${NC}"
    exit 1
fi

# Determine which CLI is available (prefer bao since we're using OpenBao)
if command -v bao &> /dev/null; then
    VAULT_CLI="bao"
elif command -v vault &> /dev/null; then
    VAULT_CLI="vault"
else
    echo -e "${RED}Error: Neither vault nor bao CLI found${NC}"
    exit 1
fi
echo "Using CLI: $VAULT_CLI"

# Get OpenBao token from Kubernetes secret
echo "📋 Getting OpenBao token from Kubernetes secret..."
OPENBAO_TOKEN=$(kubectl get secret openbao-token -n openbao -o jsonpath='{.data.token}' 2>/dev/null | base64 -d || echo "")

if [[ -z "$OPENBAO_TOKEN" ]]; then
    echo -e "${RED}Error: Could not get OpenBao token from Kubernetes${NC}"
    echo "Make sure the openbao-token secret exists in the openbao namespace"
    exit 1
fi
echo -e "${GREEN}✓ Got OpenBao token${NC}"

# Set up vault/bao CLI
export VAULT_ADDR="${VAULT_ADDR:-http://localhost:8200}"
export VAULT_TOKEN="$OPENBAO_TOKEN"

# Check OpenBao connectivity
if ! $VAULT_CLI status &>/dev/null; then
    echo -e "${RED}Error: Cannot connect to OpenBao at $VAULT_ADDR${NC}"
    echo "Make sure OpenBao is port-forwarded:"
    echo "  kubectl port-forward svc/openbao -n openbao 8200:8200"
    exit 1
fi
echo -e "${GREEN}✓ Connected to OpenBao${NC}"
echo ""

# Function to update OpenBao secret safely using separate key/value arguments
# Usage: update_openbao "path" "key1" "value1" "key2" "value2" ...
# Each key and value is passed as a separate argument to avoid shell injection
# when secret values contain special characters (quotes, =, spaces, etc.)
update_openbao() {
    local path=$1
    shift
    
    if [[ "$DRY_RUN" == "true" ]]; then
        echo "    (dry run - would update secret/${path})"
        return 0
    fi
    
    # Build key=value pairs safely by iterating through pairs
    local args=()
    while [[ $# -ge 2 ]]; do
        local key=$1
        local value=$2
        shift 2
        # Construct key=value as a single argument - the value is NOT re-parsed by shell
        args+=("${key}=${value}")
    done
    
    # Pass arguments directly to CLI using "${args[@]}" - no eval needed
    if $VAULT_CLI kv put "secret/${path}" "${args[@]}" > /dev/null 2>&1; then
        echo -e "    ${GREEN}✓ Updated secret/${path}${NC}"
        SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
        return 0
    else
        echo -e "    ${RED}✗ Failed to update secret/${path}${NC}"
        FAIL_COUNT=$((FAIL_COUNT + 1))
        return 1
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 1: Mayastor JWT Token
# ═══════════════════════════════════════════════════════════════════════════════
echo "═══════════════════════════════════════════════════════════════════════════════"
echo -e "${BLUE}SECTION 1: Mayastor JWT Token${NC}"
echo "═══════════════════════════════════════════════════════════════════════════════"

# Try to get existing JWT token from mayastor namespace
JWT_ROOT=$(kubectl get secret mayastor-etcd-jwt-token -n mayastor -o jsonpath='{.data.jwt-token-root}' 2>/dev/null | base64 -d || echo "")
JWT_SIGN_KEY=$(kubectl get secret mayastor-etcd-jwt-token -n mayastor -o jsonpath='{.data.jwt-token-sign-key}' 2>/dev/null | base64 -d || echo "")

if [[ -n "$JWT_ROOT" ]]; then
    echo "📥 Found Mayastor JWT token in Kubernetes"
    # Use the same token for sign key if not present
    [[ -z "$JWT_SIGN_KEY" ]] && JWT_SIGN_KEY="$JWT_ROOT"
    update_openbao "mayastor" "jwt-token-root" "$JWT_ROOT" "jwt-token-sign-key" "$JWT_SIGN_KEY"
else
    echo -e "${YELLOW}⚠ Mayastor JWT token not found in Kubernetes${NC}"
    echo "   This is normal if Mayastor hasn't been initialized yet"
    echo "   The token will be created when Mayastor starts"
    SKIP_COUNT=$((SKIP_COUNT + 1))
fi

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 2: SeaweedFS S3 Credentials
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo -e "${BLUE}SECTION 2: SeaweedFS S3 Credentials${NC}"
echo "═══════════════════════════════════════════════════════════════════════════════"

# Try multiple possible secret names and namespaces
S3_ACCESS=""
S3_SECRET=""

# Try seaweedfs-s3-secret in seaweedfs namespace
if kubectl get secret seaweedfs-s3-secret -n seaweedfs &>/dev/null; then
    S3_ACCESS=$(kubectl get secret seaweedfs-s3-secret -n seaweedfs -o jsonpath='{.data.admin_access_key_id}' 2>/dev/null | base64 -d || echo "")
    S3_SECRET=$(kubectl get secret seaweedfs-s3-secret -n seaweedfs -o jsonpath='{.data.admin_secret_access_key}' 2>/dev/null | base64 -d || echo "")
fi

# Try alternate field names
if [[ -z "$S3_ACCESS" ]]; then
    S3_ACCESS=$(kubectl get secret seaweedfs-s3-secret -n seaweedfs -o jsonpath='{.data.access_key}' 2>/dev/null | base64 -d || echo "")
    S3_SECRET=$(kubectl get secret seaweedfs-s3-secret -n seaweedfs -o jsonpath='{.data.secret_key}' 2>/dev/null | base64 -d || echo "")
fi

# Try loki-s3-secret in observability (might have SeaweedFS creds)
if [[ -z "$S3_ACCESS" ]] && kubectl get secret loki-s3-secret -n observability &>/dev/null; then
    S3_ACCESS=$(kubectl get secret loki-s3-secret -n observability -o jsonpath='{.data.S3_ACCESS_KEY_ID}' 2>/dev/null | base64 -d || echo "")
    S3_SECRET=$(kubectl get secret loki-s3-secret -n observability -o jsonpath='{.data.S3_SECRET_ACCESS_KEY}' 2>/dev/null | base64 -d || echo "")
fi

if [[ -n "$S3_ACCESS" && -n "$S3_SECRET" ]]; then
    echo "📥 Found SeaweedFS S3 credentials in Kubernetes"
    echo "  Access Key: ${S3_ACCESS:0:8}..."
    update_openbao "seaweedfs-s3-credentials" "access_key" "$S3_ACCESS" "secret_key" "$S3_SECRET"
else
    echo -e "${YELLOW}⚠ SeaweedFS S3 credentials not found in Kubernetes${NC}"
    echo "   This is normal if SeaweedFS hasn't been deployed yet"
    echo ""
    echo "   To manually create SeaweedFS credentials:"
    echo "   1. Generate credentials or use SeaweedFS admin creds"
    echo "   2. Store in OpenBao:"
    echo "      vault kv put secret/seaweedfs-s3-credentials access_key='ACCESS' secret_key='SECRET'"  # pragma: allowlist secret
    SKIP_COUNT=$((SKIP_COUNT + 1))
fi

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 3: Tailscale/Headscale Auth Key
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo -e "${BLUE}SECTION 3: Tailscale/Headscale Auth Key${NC}"
echo "═══════════════════════════════════════════════════════════════════════════════"

# Check if existing auth key exists
TS_AUTHKEY=$(kubectl get secret tailscale-auth -n headscale -o jsonpath='{.data.TS_AUTHKEY}' 2>/dev/null | base64 -d || echo "")

if [[ -n "$TS_AUTHKEY" ]]; then
    echo "📥 Found existing Tailscale auth key in Kubernetes"
    update_openbao "tailscale-auth" "TS_AUTHKEY" "$TS_AUTHKEY"
else
    echo "🔑 Generating new Headscale pre-auth key..."
    
    # Try to generate a new key from Headscale
    if kubectl get deploy headscale -n headscale &>/dev/null; then
        NEW_KEY=$(kubectl exec -n headscale deploy/headscale -- headscale preauthkeys create --user admin --reusable --expiration 8760h 2>/dev/null || echo "")
        
        if [[ -n "$NEW_KEY" ]]; then
            echo "📥 Generated new Headscale pre-auth key"
            update_openbao "tailscale-auth" "TS_AUTHKEY" "$NEW_KEY"
        else
            echo -e "${YELLOW}⚠ Could not generate Headscale pre-auth key${NC}"
            echo "   Headscale may not be fully initialized"
            echo ""
            echo "   To manually create:"
            echo "   1. kubectl exec -n headscale deploy/headscale -- headscale preauthkeys create --user admin --reusable --expiration 8760h"
            echo "   2. vault kv put secret/tailscale-auth TS_AUTHKEY='<key-from-above>'"
            SKIP_COUNT=$((SKIP_COUNT + 1))
        fi
    else
        echo -e "${YELLOW}⚠ Headscale deployment not found${NC}"
        SKIP_COUNT=$((SKIP_COUNT + 1))
    fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 4: Tools Kubernetes (kubeconfig for MCP server)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo -e "${BLUE}SECTION 4: Tools Kubernetes (kubeconfig)${NC}"
echo "═══════════════════════════════════════════════════════════════════════════════"

# Check if tools-kubernetes secret already exists with kubeconfig
EXISTING_KUBECONFIG=$(kubectl get secret tools-kubernetes-secrets -n cto -o jsonpath='{.data.KUBECONFIG}' 2>/dev/null | base64 -d || echo "")

if [[ -n "$EXISTING_KUBECONFIG" ]]; then
    echo "📥 Found existing kubeconfig in Kubernetes secret"
    update_openbao "tools-kubernetes" "KUBECONFIG" "$EXISTING_KUBECONFIG"
else
    echo -e "${YELLOW}⚠ Tools kubeconfig not found${NC}"
    echo ""
    echo "   The tools-kubernetes secret requires a kubeconfig for the MCP server."
    echo "   This should be a service account based kubeconfig with limited permissions."
    echo ""
    echo "   To create a service account kubeconfig:"
    echo "   1. Create a ServiceAccount and ClusterRoleBinding"
    echo "   2. Extract the token and CA cert"
    echo "   3. Generate kubeconfig and store in OpenBao:"
    echo "      vault kv put secret/tools-kubernetes KUBECONFIG='<base64-kubeconfig>'"
    SKIP_COUNT=$((SKIP_COUNT + 1))
fi

# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "  SUMMARY"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${YELLOW}Dry run complete. Run without --dry-run to apply changes.${NC}"
else
    echo -e "  ${GREEN}✓ Successful:${NC} $SUCCESS_COUNT secrets"
    echo -e "  ${YELLOW}⚠ Skipped:${NC}    $SKIP_COUNT items (not found or need manual setup)"
    echo -e "  ${RED}✗ Failed:${NC}     $FAIL_COUNT secrets"
fi

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "  NEXT STEPS"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Force refresh all ExternalSecrets:"
echo "   kubectl get externalsecrets -A -o name | xargs -I {} kubectl annotate {} force-sync=\$(date +%s) --overwrite"
echo ""
echo "2. Verify ArgoCD application health:"
echo "   argocd app get external-secrets-config --grpc-web"
echo ""
echo "3. Check all ExternalSecrets are synced:"
echo "   kubectl get externalsecrets -A | grep -v SecretSynced"
echo ""
