#!/usr/bin/env bash
set -euo pipefail# =============================================================================
# sync-secrets-for-dev.sh - Fetch secrets from 1Password for local development
# =============================================================================
# This script fetches secrets from 1Password and writes them to .env.local
# for use in local development. The .env.local file is gitignored.
#
# Prerequisites:
#   - 1Password CLI (op) installed: brew install 1password-cli
#   - Signed in to 1Password: op signin
#
# Usage:
#   ./scripts/sync-secrets-for-dev.sh
#   source .env.local
#   just dev
#
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
OUTPUT_FILE=".env.local"
VAULT_NAME="5D Labs"  # Adjust to your 1Password vault name

# 1Password item names (adjust these to match your 1Password items)
OP_ITEM_API_KEYS="CTO API Keys"  # pragma: allowlist secret
OP_ITEM_LINEAR="Linear Integration"
OP_ITEM_GITHUB="GitHub PAT"
OP_ITEM_FIRECRAWL="Firecrawl"
OP_ITEM_TWITTER="Twitter Research"
OP_ITEM_LATITUDE="Latitude.sh"

echo -e "${BLUE}=== CTO Platform - Secrets Sync ===${NC}"
echo ""

# Check if 1Password CLI is installed
if ! command -v op &> /dev/null; then
    echo -e "${RED}Error: 1Password CLI (op) is not installed${NC}"
    echo "Install it with: brew install 1password-cli"
    echo ""
    echo "Alternatively, create .env.local manually using .env.template as a reference."
    exit 1
fi

# Check if signed in to 1Password
if ! op account list &> /dev/null; then
    echo -e "${YELLOW}Not signed in to 1Password. Signing in...${NC}"
    eval $(op signin)
fi

echo -e "${BLUE}Fetching secrets from 1Password...${NC}"
echo ""

# Start building the .env.local file
cat > "$OUTPUT_FILE" << 'HEADER'
# =============================================================================
# .env.local - Local Development Environment Variables
# =============================================================================
# Generated by: ./scripts/sync-secrets-for-dev.sh
# This file is gitignored and should not be committed.
#
# Usage:
#   source .env.local
#   just dev
# =============================================================================

HEADER

# Function to safely get a secret (returns empty string if not found)
get_secret() {
    local item="$1"
    local field="$2"
    local vault="${3:-$VAULT_NAME}"
    
    op item get "$item" --vault "$vault" --fields "$field" 2>/dev/null || echo ""
}

# Function to write a secret to the env file
write_secret() {
    local name="$1"
    local value="$2"
    local description="$3"
    
    if [ -n "$value" ]; then
        echo "# $description" >> "$OUTPUT_FILE"
        echo "export $name=\"$value\"" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo -e "  ${GREEN}✓${NC} $name"
    else
        echo -e "  ${YELLOW}⚠${NC} $name (not found - add manually)"
        echo "# $description (NOT FOUND - add manually)" >> "$OUTPUT_FILE"
        echo "# export $name=\"\"" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
}

# =============================================================================
# Kubernetes Configuration
# =============================================================================
echo -e "\n${BLUE}Kubernetes Configuration${NC}"
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# Kubernetes Configuration
# =============================================================================
# Path to your kubeconfig (usually set automatically)
# export KUBECONFIG="$HOME/.kube/config"

# Namespace for CTO platform
export NAMESPACE="cto"
export KUBERNETES_NAMESPACE="cto"

# Logging
export RUST_LOG="info,controller=debug,pm=debug,healer=debug,tools=debug"

EOF
echo -e "  ${GREEN}✓${NC} NAMESPACE=cto"
echo -e "  ${GREEN}✓${NC} RUST_LOG configured"

# =============================================================================
# AI Provider API Keys
# =============================================================================
echo -e "\n${BLUE}AI Provider API Keys${NC}"
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# AI Provider API Keys (from 1Password: api-keys)
# =============================================================================
EOF

# Try to fetch from 1Password, fall back to manual entry
ANTHROPIC_KEY=$(get_secret "$OP_ITEM_API_KEYS" "ANTHROPIC_API_KEY" 2>/dev/null || echo "")
OPENAI_KEY=$(get_secret "$OP_ITEM_API_KEYS" "OPENAI_API_KEY" 2>/dev/null || echo "")
GEMINI_KEY=$(get_secret "$OP_ITEM_API_KEYS" "GEMINI_API_KEY" 2>/dev/null || echo "")
GOOGLE_KEY=$(get_secret "$OP_ITEM_API_KEYS" "GOOGLE_API_KEY" 2>/dev/null || echo "")
CURSOR_KEY=$(get_secret "$OP_ITEM_API_KEYS" "CURSOR_API_KEY" 2>/dev/null || echo "")
CONTEXT7_KEY=$(get_secret "$OP_ITEM_API_KEYS" "CONTEXT7_API_KEY" 2>/dev/null || echo "")
PERPLEXITY_KEY=$(get_secret "$OP_ITEM_API_KEYS" "PERPLEXITY_API_KEY" 2>/dev/null || echo "")
XAI_KEY=$(get_secret "$OP_ITEM_API_KEYS" "XAI_API_KEY" 2>/dev/null || echo "")
FACTORY_KEY=$(get_secret "$OP_ITEM_API_KEYS" "FACTORY_API_KEY" 2>/dev/null || echo "")
BRAVE_KEY=$(get_secret "$OP_ITEM_API_KEYS" "BRAVE_API_KEY" 2>/dev/null || echo "")
MINIMAX_KEY=$(get_secret "$OP_ITEM_API_KEYS" "MINIMAX_API_KEY" 2>/dev/null || echo "")
MINIMAX_GROUP=$(get_secret "$OP_ITEM_API_KEYS" "MINIMAX_GROUP_ID" 2>/dev/null || echo "")

write_secret "ANTHROPIC_API_KEY" "$ANTHROPIC_KEY" "Anthropic/Claude API"
write_secret "OPENAI_API_KEY" "$OPENAI_KEY" "OpenAI API"
write_secret "GEMINI_API_KEY" "$GEMINI_KEY" "Google Gemini API"
write_secret "GOOGLE_API_KEY" "$GOOGLE_KEY" "Google Cloud API"
write_secret "CURSOR_API_KEY" "$CURSOR_KEY" "Cursor IDE API"
write_secret "CONTEXT7_API_KEY" "$CONTEXT7_KEY" "Context7 Documentation API"
write_secret "PERPLEXITY_API_KEY" "$PERPLEXITY_KEY" "Perplexity Search API"
write_secret "XAI_API_KEY" "$XAI_KEY" "xAI/Grok API"
write_secret "FACTORY_API_KEY" "$FACTORY_KEY" "Factory AI API"
write_secret "BRAVE_API_KEY" "$BRAVE_KEY" "Brave Search API"
write_secret "MINIMAX_API_KEY" "$MINIMAX_KEY" "MiniMax AI API"
write_secret "MINIMAX_GROUP_ID" "$MINIMAX_GROUP" "MiniMax Group ID"

# =============================================================================
# Linear Integration
# =============================================================================
echo -e "\n${BLUE}Linear Integration${NC}"
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# Linear Integration (from 1Password: linear-sync)
# =============================================================================
export LINEAR_ENABLED="true"
export LINEAR_PORT="8081"
export LINEAR_TEAM_ID="CTOPA"

EOF

LINEAR_API=$(get_secret "$OP_ITEM_LINEAR" "LINEAR_API_KEY" 2>/dev/null || echo "")
LINEAR_CLIENT_ID=$(get_secret "$OP_ITEM_LINEAR" "LINEAR_CLIENT_ID" 2>/dev/null || echo "")
LINEAR_CLIENT_SECRET=$(get_secret "$OP_ITEM_LINEAR" "LINEAR_CLIENT_SECRET" 2>/dev/null || echo "")
LINEAR_OAUTH=$(get_secret "$OP_ITEM_LINEAR" "LINEAR_OAUTH_TOKEN" 2>/dev/null || echo "")
LINEAR_WEBHOOK=$(get_secret "$OP_ITEM_LINEAR" "LINEAR_WEBHOOK_SECRET" 2>/dev/null || echo "")

write_secret "LINEAR_API_KEY" "$LINEAR_API" "Linear API Key"
write_secret "LINEAR_CLIENT_ID" "$LINEAR_CLIENT_ID" "Linear OAuth Client ID"
write_secret "LINEAR_CLIENT_SECRET" "$LINEAR_CLIENT_SECRET" "Linear OAuth Client Secret"
write_secret "LINEAR_OAUTH_TOKEN" "$LINEAR_OAUTH" "Linear OAuth Access Token"
write_secret "LINEAR_WEBHOOK_SECRET" "$LINEAR_WEBHOOK" "Linear Webhook Signing Secret"

# =============================================================================
# GitHub Integration
# =============================================================================
echo -e "\n${BLUE}GitHub Integration${NC}"
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# GitHub Integration (from 1Password: tools-github)
# =============================================================================
EOF

GITHUB_PAT=$(get_secret "$OP_ITEM_GITHUB" "GITHUB_PERSONAL_ACCESS_TOKEN" 2>/dev/null || echo "")
write_secret "GITHUB_TOKEN" "$GITHUB_PAT" "GitHub Personal Access Token"
write_secret "GITHUB_PERSONAL_ACCESS_TOKEN" "$GITHUB_PAT" "GitHub PAT (alias)"
write_secret "GH_TOKEN" "$GITHUB_PAT" "GitHub PAT (gh cli)"

# =============================================================================
# Firecrawl
# =============================================================================
echo -e "\n${BLUE}Firecrawl${NC}"
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# Firecrawl (from 1Password: tools-firecrawl)
# =============================================================================
EOF

FIRECRAWL_KEY=$(get_secret "$OP_ITEM_FIRECRAWL" "FIRECRAWL_API_KEY" 2>/dev/null || echo "")
write_secret "FIRECRAWL_API_KEY" "$FIRECRAWL_KEY" "Firecrawl Web Scraping API"

# =============================================================================
# Latitude.sh
# =============================================================================
echo -e "\n${BLUE}Latitude.sh${NC}"
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# Latitude.sh (from 1Password: tools-latitude)
# =============================================================================
EOF

LATITUDE_KEY=$(get_secret "$OP_ITEM_LATITUDE" "LATITUDE_API_KEY" 2>/dev/null || echo "")
write_secret "LATITUDE_API_KEY" "$LATITUDE_KEY" "Latitude.sh Bare Metal API"

# =============================================================================
# Twitter Research (optional)
# =============================================================================
echo -e "\n${BLUE}Twitter Research (optional)${NC}"
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# Twitter Research (from 1Password: research-twitter)
# Only needed for research CLI
# =============================================================================
EOF

TWITTER_AUTH=$(get_secret "$OP_ITEM_TWITTER" "TWITTER_AUTH_TOKEN" 2>/dev/null || echo "")
TWITTER_CT0=$(get_secret "$OP_ITEM_TWITTER" "TWITTER_CT0" 2>/dev/null || echo "")
write_secret "TWITTER_AUTH_TOKEN" "$TWITTER_AUTH" "Twitter Auth Token"
write_secret "TWITTER_CT0" "$TWITTER_CT0" "Twitter CT0 CSRF Token"

# =============================================================================
# Service Configuration
# =============================================================================
cat >> "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# Service Configuration
# =============================================================================

# Controller
export SERVER_HOST="0.0.0.0"
export SERVER_PORT="8080"
export AGENT_TEMPLATES_PATH="./templates"

# Healer
export HEALER_TEMPLATES_DIR="./templates/healer"
export CTO_CONFIG_PATH="./cto-config.json"

# Tools
export PORT="3000"
export SYSTEM_CONFIG_PATH="./infra/charts/cto/templates/tools"

EOF

echo -e "\n${GREEN}=== Sync Complete ===${NC}"
echo ""
echo "Environment file written to: $OUTPUT_FILE"
echo ""
echo "Next steps:"
echo "  1. Review $OUTPUT_FILE and fill in any missing values"
echo "  2. Run: source $OUTPUT_FILE"
echo "  3. Run: just dev (or just dev-pm, just dev-controller, etc.)"
echo ""
echo -e "${YELLOW}Note: Some secrets may not have been found in 1Password.${NC}"
echo "Check the file for any commented-out exports and add them manually."
