/**
 * Generate Task Documentation Operation
 * Creates full documentation structure for each task
 */

import type { GeneratedTask } from '../types';
import * as fs from 'fs/promises';
import * as path from 'path';

interface GenerateDocsPayload {
  tasks: GeneratedTask[];
  base_path: string;
  project_root: string;
}

interface GeneratedDoc {
  task_id: number;
  files: string[];
}

/**
 * Generate task.md (spec + decision points) for a task
 */
function generateTaskMarkdown(task: GeneratedTask): string {
  const decisionPoints = task.decision_points && task.decision_points.length > 0
    ? `\n## Decision Points\n\n${task.decision_points.map((dp, idx) => `### ${idx + 1}. ${dp.description}

- **Category:** ${dp.category}
- **Constraint Type:** ${dp.constraint_type}
- **Requires Approval:** ${dp.requires_approval ? 'Yes' : 'No'}
- **Options:** ${dp.options.join(', ')}

`).join('\n')}`
    : '';

  const subtasks = task.subtasks && task.subtasks.length > 0
    ? `\n## Subtasks\n\n${task.subtasks.map(st => `- **${st.id}:** ${st.title}`).join('\n')}`
    : '';

  return `# Task ${task.id}: ${task.title}

## Overview
${task.description}

## Details
${task.details || 'No additional details provided.'}${decisionPoints}

## Testing Strategy
${task.test_strategy || 'Not specified.'}${subtasks}

## Metadata
- **ID:** ${task.id}
- **Priority:** ${task.priority || 'medium'}
- **Status:** ${task.status || 'pending'}
- **Dependencies:** ${task.dependencies.length > 0 ? task.dependencies.join(', ') : 'None'}

---
*Generated by intake-agent*
`;
}

/**
 * Generate prompt.md for implementation
 */
function generatePromptMarkdown(task: GeneratedTask): string {
  const agentHint = task.title.match(/\(([A-Za-z]+)\s*-\s*([^)]+)\)/);
  const agentName = agentHint ? agentHint[1] : 'implementer';
  const techStack = agentHint ? agentHint[2] : '';

  const dependencies = task.dependencies.length > 0
    ? `\n**Dependencies:** Complete tasks ${task.dependencies.join(', ')} first.`
    : '';

  return `# Implementation Prompt: Task ${task.id}

**Agent:** ${agentName}
**Tech Stack:** ${techStack}
**Status:** ${task.status || 'pending'}${dependencies}

## What to Build
${task.description}

## Implementation Details
${task.details || 'Implement according to the specifications in the project documentation.'}

## Testing Requirements
${task.test_strategy || 'Ensure the implementation passes all existing tests and add new tests as needed.'}

## Acceptance Criteria
- [ ] Implementation complete
- [ ] Tests passing
- [ ] Code reviewed
- [ ] Documentation updated

---
*Generated by intake-agent - implement this task*
`;
}

/**
 * Generate acceptance.md for a task
 */
function generateAcceptanceMarkdown(task: GeneratedTask): string {
  const dependencies = task.dependencies.length > 0 
    ? `\n- **Dependencies:** Tasks ${task.dependencies.join(', ')} must be completed first`
    : '';
  
  return `# Acceptance Criteria: ${task.title}

## Task ID: ${task.id}
${task.priority ? `- **Priority:** ${task.priority}` : ''}${dependencies}

## Description
${task.description}

## Details
${task.details || 'No additional details provided.'}

## Testing Strategy
${task.test_strategy || 'No specific testing strategy defined.'}

## Subtasks
${task.subtasks && task.subtasks.length > 0 
  ? task.subtasks.map(st => `- [ ] ${st.title}`).join('\n')
  : 'No subtasks defined.'}

---
*Generated by intake-agent*
`;
}

/**
 * Generate decisions.md for a task
 */
function generateDecisionsMarkdown(task: GeneratedTask): string {
  if (!task.decision_points || task.decision_points.length === 0) {
    return `# Implementation Decisions: ${task.title}

No decision points required for this task.

---
*Generated by intake-agent*
`;
  }

  const decisions = task.decision_points.map((dp, idx) => {
    const approval = dp.requires_approval 
      ? '**Requires approval before proceeding**'
      : '**Can proceed without approval**';
    
    return `## Decision ${idx + 1}: ${dp.description}

- **Category:** ${dp.category}
- **Constraint Type:** ${dp.constraint_type}
- ${approval}

### Options
${dp.options.map(opt => `- ${opt}`).join('\n')}

---
`;
  }).join('\n');

  return `# Implementation Decisions: ${task.title}

This document captures architectural and implementation decisions made during the planning phase.

${decisions}
---
*Generated by intake-agent*
`;
}

/**
 * Generate prompt.xml for a task
 */
function generatePromptXml(task: GeneratedTask): string {
  const subtasks = task.subtasks && task.subtasks.length > 0
    ? `\n  <subtasks>\n${task.subtasks.map(st => `    <subtask id="${st.id}" title="${st.title}">
      <description>${st.description}</description>
      <status>${st.status || 'pending'}</status>
      <test_strategy>${st.test_strategy || ''}</test_strategy>
    </subtask>`).join('\n')}\n  </subtasks>`
    : '';

  const decisionPoints = task.decision_points && task.decision_points.length > 0
    ? `\n  <decision_points>\n${task.decision_points.map(dp => `    <decision id="${dp.id}" category="${dp.category}" constraint_type="${dp.constraint_type}" requires_approval="${dp.requires_approval}">
      <description>${dp.description}</description>
      <options>${dp.options.join(', ')}</options>
    </decision>`).join('\n')}\n  </decision_points>`
    : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<task xmlns="https://cto.5dlabs.ai/task">
  <id>${task.id}</id>
  <title>${task.title}</title>
  <description>${task.description}</description>
  <priority>${task.priority || 'medium'}</priority>
  <dependencies>${task.dependencies.join(', ')}</dependencies>
  <status>${task.status || 'pending'}</status>
  <details>${task.details || ''}</details>
  <test_strategy>${task.test_strategy || ''}</test_strategy>${subtasks}${decisionPoints}
</task>
`;
}

/**
 * Generate all documentation for a task
 */
async function generateTaskDocs(
  task: GeneratedTask,
  basePath: string
): Promise<GeneratedDoc> {
  const taskDir = path.join(basePath, `task-${task.id}`);
  const files: string[] = [];
  
  await fs.mkdir(taskDir, { recursive: true });
  
  // Generate all docs
  const docGenerators = [
    { name: 'task.md', content: generateTaskMarkdown(task) },
    { name: 'prompt.md', content: generatePromptMarkdown(task) },
    { name: 'acceptance.md', content: generateAcceptanceMarkdown(task) },
    { name: 'decisions.md', content: generateDecisionsMarkdown(task) },
    { name: 'prompt.xml', content: generatePromptXml(task) },
  ];
  
  for (const doc of docGenerators) {
    await fs.writeFile(path.join(taskDir, doc.name), doc.content);
    files.push(`task-${task.id}/${doc.name}`);
  }
  
  // Generate subtask docs
  if (task.subtasks && task.subtasks.length > 0) {
    const subtasksDir = path.join(taskDir, 'subtasks');
    await fs.mkdir(subtasksDir, { recursive: true });
    
    for (const subtask of task.subtasks) {
      const subtaskDir = path.join(subtasksDir, `task-${subtask.id}`);
      await fs.mkdir(subtaskDir, { recursive: true });
      
      await fs.writeFile(
        path.join(subtaskDir, 'prompt.md'),
        `# Subtask ${subtask.id}: ${subtask.title}

## Description
${subtask.description}

## Details
${subtask.details || 'No details provided.'}

## Testing
${subtask.test_strategy || 'No testing strategy defined.'}

## Parent Task
Task ${task.id}: ${task.title}

---
*Generated by intake-agent - subtask of task ${task.id}*
`
      );
      files.push(`task-${task.id}/subtasks/task-${subtask.id}/prompt.md`);
    }
  }
  
  return { task_id: task.id, files };
}

/**
 * Main operation: Generate documentation for all tasks
 */
export async function generateDocs(
  payload: GenerateDocsPayload
): Promise<{
  success: boolean;
  generated_docs?: GeneratedDoc[];
  error?: string;
}> {
  const { tasks, base_path } = payload;
  
  if (!Array.isArray(tasks) || tasks.length === 0) {
    return { success: false, error: 'No tasks provided' };
  }
  
  if (!base_path) {
    return { success: false, error: 'Missing base_path' };
  }
  
  try {
    const results: GeneratedDoc[] = [];
    
    for (const task of tasks) {
      const result = await generateTaskDocs(task, base_path);
      results.push(result);
    }
    
    return {
      success: true,
      generated_docs: results,
    };
  } catch (e) {
    const error = e instanceof Error ? e.message : 'Unknown error';
    return { success: false, error: `Doc generation failed: ${error}` };
  }
}
