#!/usr/bin/env bash
# Create intake/local.env.op when missing, from a committed template or env — no manual cp.
#
# `op://…` lines are **pointers**, not secret values; teams can commit
# intake/local.env.op.defaults with real paths so clone → checkpoints "just works".
#
# Disable: INTAKE_OP_BOOTSTRAP_DISABLE=1

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_LOCAL="$ROOT/intake/local.env.op"
ENV_DEFAULTS="$ROOT/intake/local.env.op.defaults"

[[ "${INTAKE_OP_BOOTSTRAP_DISABLE:-}" == "1" || "${INTAKE_OP_BOOTSTRAP_DISABLE:-}" == "true" ]] && exit 0
[[ -f "$ENV_LOCAL" ]] && exit 0

if [[ -f "$ENV_DEFAULTS" ]]; then
  cp "$ENV_DEFAULTS" "$ENV_LOCAL"
  echo "intake: created intake/local.env.op from intake/local.env.op.defaults" >&2
  exit 0
fi

if [[ -n "${INTAKE_BOOTSTRAP_LINEAR_OP_REF:-}" ]]; then
  {
    echo "# Generated by ensure-local-env-op.sh from INTAKE_BOOTSTRAP_LINEAR_OP_REF"
    echo "LINEAR_API_KEY=${INTAKE_BOOTSTRAP_LINEAR_OP_REF}"
  } >"$ENV_LOCAL"
  echo "intake: created intake/local.env.op from INTAKE_BOOTSTRAP_LINEAR_OP_REF" >&2
  exit 0
fi

exit 0
