#!/usr/bin/env bash
# generate-storybook.sh — Build a per-project Storybook scaffold from
# component-library.json. Emits a runnable Storybook (Next.js) and, when
# Expo is targeted, a parallel React Native Storybook scaffold + static
# manifest.json (RN does not support the Storybook MCP addon yet).
#
# Usage: generate-storybook.sh <workspace_root> <project_name>
#
# Inputs (under <workspace_root>/.tasks/design/):
#   - component-library.json   (required; produced by intake)
#   - oss-catalog.json         (optional; stamped into scaffolds for MCP/agents)
#
# Outputs (under <workspace_root>/.tasks/design/storybook/):
#   - AGENTS.md                                 (top-level workflow doc)
#   - web/                                      (when frameworks ∋ nextjs|shared)
#       package.json, .storybook/{main,preview}.ts,
#       src/tokens/tokens.css,
#       src/components/<Name>/<Name>.{tsx,stories.tsx},
#       oss-catalog.json (copy)
#   - native/                                   (when frameworks ∋ expo)
#       package.json, manifest.json,
#       oss-catalog.json (copy), AGENTS.md
#
# Idempotent: rewrites the storybook/ tree on every run.
set -euo pipefail

ROOT="${1:-.}"
PROJECT="${2:-project}"

DESIGN_DIR="$ROOT/.tasks/design"
LIB="$DESIGN_DIR/component-library.json"
OSS_CATALOG="$DESIGN_DIR/oss-catalog.json"
OUT="$DESIGN_DIR/storybook"

if [ ! -f "$LIB" ]; then
  echo "generate-storybook: component-library.json not found at $LIB; skipping." >&2
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "generate-storybook: jq is required" >&2
  exit 1
fi

mkdir -p "$OUT"

# Determine targets from frameworks[].
WANT_WEB=$(jq -r '(.frameworks // []) | any(. == "nextjs" or . == "shared")' "$LIB")
WANT_NATIVE=$(jq -r '(.frameworks // []) | any(. == "expo")' "$LIB")

# ---- shadcn-selections.json ----------------------------------------------
# Derived from component_map[].shadcn entries. Consumed by:
#   - the TOOLS.md design-context appender (harness templates), and
#   - frontend agents at implementation time:
#       jq -r '.components[].url' .tasks/design/shadcn-selections.json \
#         | xargs -I{} npx shadcn add {}
# Always emitted (even when empty) so downstream consumers can rely on it.
jq '{
  registries: (
    [ (.component_map // [])[]
      | .shadcn?.registry // empty ] | unique
  ),
  components: [
    (.component_map // [])[]
    | select(.shadcn != null)
    | {
        name: (.shadcn.name // .name),
        registry: .shadcn.registry,
        url: (.shadcn.url // null),
        framework: (.framework // "shared")
      }
  ]
}' "$LIB" >"$DESIGN_DIR/shadcn-selections.json"

# ---- helpers --------------------------------------------------------------

# pascal-case a name (strip non-alphanum, capitalize words). Falls back to "Component".
pascal() {
  printf '%s' "$1" | awk '
    {
      n=split($0, a, /[^A-Za-z0-9]+/);
      out="";
      for (i=1;i<=n;i++) {
        if (length(a[i]) > 0) {
          out = out toupper(substr(a[i],1,1)) tolower(substr(a[i],2));
        }
      }
      if (length(out)==0) out="Component";
      # Ensure leading char is a letter.
      if (out ~ /^[0-9]/) out = "C" out;
      print out;
    }'
}

# Render a CSS custom property block from a flat token group.
render_token_group() {
  local group="$1" prefix="$2"
  jq -r --arg prefix "$prefix" '
    .[$ARGS.positional[0]] // {} | to_entries[] |
    "  --" + $prefix + "-" + (.key | gsub("[^A-Za-z0-9]+"; "-")) + ": " + (
      if (.value | type) == "string" then .value
      elif (.value | type) == "number" then (.value | tostring)
      else (.value | tostring)
      end
    ) + ";"
  ' --args "$group" "$LIB" 2>/dev/null || true
}

# ---- AGENTS.md (top level) -----------------------------------------------

cat >"$OUT/AGENTS.md" <<EOF
# Storybook — ${PROJECT}

This directory is the project-scoped component library, generated by the intake
pipeline from \`.tasks/design/component-library.json\`.

## Layout

- \`web/\`    — Next.js Storybook with the \`@storybook/addon-mcp\` MCP server
  (default endpoint \`http://localhost:6006/mcp\`).
- \`native/\` — React Native (Expo) Storybook scaffold. The Storybook MCP addon
  does **not** support React Native yet; agents read \`native/manifest.json\`
  directly until upstream support lands.

## Frontend agent workflow (Blaze)

1. \`cd storybook/web && npm install && npm run storybook &\`
2. Register the MCP server with your harness:
   \`mcp add ${PROJECT}-sb-mcp http://localhost:6006/mcp\`
3. Discover components via MCP:
   - \`list-all-documentation\`
   - \`get-documentation { component, story? }\`
4. shadcn-sourced components: install with
   \`npx shadcn add <url>\` using the URLs in
   \`.tasks/design/shadcn-selections.json\` (when present) or the entries in
   \`web/oss-catalog.json\`.

The component inventory, props, and states in here are the source of truth for
the implementation phase. Do not invent components that are not listed.
EOF

# ---- Web scaffold ---------------------------------------------------------

if [ "$WANT_WEB" = "true" ]; then
  WEB="$OUT/web"
  rm -rf "$WEB"
  mkdir -p "$WEB/.storybook" "$WEB/src/tokens" "$WEB/src/components"

  # package.json
  cat >"$WEB/package.json" <<'EOF'
{
  "name": "project-storybook-web",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "next": "^15.0.0"
  },
  "devDependencies": {
    "storybook": "^8.3.0",
    "@storybook/nextjs-vite": "^8.3.0",
    "@storybook/addon-essentials": "^8.3.0",
    "@storybook/addon-mcp": "^0.1.0",
    "typescript": "^5.5.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0"
  }
}
EOF

  # .storybook/main.ts
  cat >"$WEB/.storybook/main.ts" <<'EOF'
import type { StorybookConfig } from '@storybook/nextjs-vite';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-mcp',
  ],
  framework: {
    name: '@storybook/nextjs-vite',
    options: {},
  },
  docs: { autodocs: 'tag' },
};

export default config;
EOF

  # .storybook/preview.ts
  cat >"$WEB/.storybook/preview.ts" <<'EOF'
import type { Preview } from '@storybook/react';
import '../src/tokens/tokens.css';

const preview: Preview = {
  parameters: {
    controls: { matchers: { color: /(background|color)$/i, date: /Date$/i } },
  },
};

export default preview;
EOF

  # tokens.css
  {
    printf ':root {\n'
    for grp in color spacing radius typography shadow; do
      jq -r --arg g "$grp" '
        (.tokens[$g] // {}) | to_entries[] |
        "  --" + $g + "-" + (.key | gsub("[^A-Za-z0-9]+"; "-")) + ": " + (
          if (.value|type)=="string" then .value
          elif (.value|type)=="number" then (.value|tostring)
          else (.value|tostring) end
        ) + ";"
      ' "$LIB" 2>/dev/null || true
    done
    printf '}\n'
  } >"$WEB/src/tokens/tokens.css"

  # Build a lookup of shadcn-mapped components → registry URL (web framework).
  SHADCN_MAP=$(jq -c '
    [ (.component_map // [])[]
      | select(.framework == null or .framework == "nextjs" or .framework == "shared")
      | select(.shadcn != null)
      | { (.name): { registry: .shadcn.registry, name: .shadcn.name, url: (.shadcn.url // null) } }
    ] | add // {}
  ' "$LIB")

  # Iterate primitives + patterns; emit component stub + stories.
  jq -c '(.primitives // []) + (.patterns // []) | .[]' "$LIB" | while IFS= read -r item; do
    NAME=$(printf '%s' "$item" | jq -r '.name')
    [ -z "$NAME" ] && continue
    P=$(pascal "$NAME")
    DIR="$WEB/src/components/$P"
    mkdir -p "$DIR"

    DESC=$(printf '%s' "$item" | jq -r '.description // ""')
    SHADCN_ENTRY=$(printf '%s' "$SHADCN_MAP" | jq -c --arg n "$NAME" '.[$n] // null')

    # Component file
    if [ "$SHADCN_ENTRY" != "null" ]; then
      SH_NAME=$(printf '%s' "$SHADCN_ENTRY" | jq -r '.name')
      cat >"$DIR/${P}.tsx" <<EOF
// Sourced from a shadcn-compatible registry. Run \`npx shadcn add\` per
// .tasks/design/shadcn-selections.json before importing in app code.
export { ${P} } from '@/components/ui/${SH_NAME}';
export type { ${P}Props } from '@/components/ui/${SH_NAME}';
EOF
    else
      # Build a TS props interface from props[].
      PROPS_TS=$(printf '%s' "$item" | jq -r '
        (.props // []) as $p
        | if ($p|length)==0 then "  children?: React.ReactNode;"
          else
            ($p | map(
              "  " + .name + (if (.required // false) then "" else "?" end) + ": " + .type + ";"
              + (if .description then "  // " + .description else "" end)
            ) | join("\n"))
          end
      ')
      cat >"$DIR/${P}.tsx" <<EOF
import * as React from 'react';

export interface ${P}Props {
${PROPS_TS}
}

/**
 * ${P}
 * ${DESC}
 *
 * Stub generated by intake. Replace with the real implementation; the
 * Storybook stories alongside this file enumerate the required states.
 */
export function ${P}(props: ${P}Props) {
  return <div data-component="${P}">{('children' in props) ? (props as any).children : null}</div>;
}
EOF
    fi

    # Stories file — one story per state, default args from props[].default.
    DEFAULT_ARGS=$(printf '%s' "$item" | jq -c '
      (.props // []) | map(select(.default != null)) | map({(.name): .default}) | add // {}
    ')
    STATES=$(printf '%s' "$item" | jq -r '(.states // ["default"]) | .[]')
    [ -z "$STATES" ] && STATES="default"

    {
      cat <<EOF
import type { Meta, StoryObj } from '@storybook/react';
import { ${P} } from './${P}';

const meta: Meta<typeof ${P}> = {
  title: 'Components/${P}',
  component: ${P},
  tags: ['autodocs'],
  args: ${DEFAULT_ARGS},
};
export default meta;

type Story = StoryObj<typeof ${P}>;

EOF
      while IFS= read -r ST; do
        [ -z "$ST" ] && continue
        SP=$(pascal "$ST")
        printf "export const %s: Story = { args: { /* state: %s */ } };\n\n" "$SP" "$ST"
      done <<<"$STATES"
    } >"$DIR/${P}.stories.tsx"
  done

  # Stamp oss-catalog.json into scaffold for MCP/agent discovery.
  if [ -f "$OSS_CATALOG" ]; then
    cp "$OSS_CATALOG" "$WEB/oss-catalog.json"
  fi
fi

# ---- Native scaffold (Expo) ----------------------------------------------

if [ "$WANT_NATIVE" = "true" ]; then
  NAT="$OUT/native"
  rm -rf "$NAT"
  mkdir -p "$NAT"

  cat >"$NAT/package.json" <<'EOF'
{
  "name": "project-storybook-native",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "storybook": "echo 'Run via Expo entry point; see AGENTS.md'"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-native": "0.74.0",
    "expo": "^51.0.0",
    "@storybook/react-native": "^7.6.0"
  }
}
EOF

  # Static manifest.json — components, states, props. Agents read this
  # directly because the Storybook MCP addon does not support RN yet.
  jq --arg project "$PROJECT" '
    {
      project: $project,
      generated_from: "component-library.json",
      framework: "expo",
      mcp_supported: false,
      components: (
        ((.primitives // []) + (.patterns // []))
        | map({
            name: .name,
            description: (.description // ""),
            states: (.states // ["default"]),
            props: (.props // []),
            tokens_used: (.tokens_used // [])
          })
      ),
      tokens: (.tokens // {}),
      shadcn: (.shadcn // {})
    }
  ' "$LIB" >"$NAT/manifest.json"

  cat >"$NAT/AGENTS.md" <<EOF
# Storybook — ${PROJECT} (React Native)

The Storybook MCP addon does **not** support React Native at this time.

Until upstream support lands, frontend agents should read \`manifest.json\` in
this directory as the source of truth for components, states, props, and
tokens. Treat each \`components[]\` entry as a contract to satisfy.

When MCP support lands, this scaffold will be regenerated to expose the same
\`list-all-documentation\` / \`get-documentation\` interface as the web target.
EOF

  if [ -f "$OSS_CATALOG" ]; then
    cp "$OSS_CATALOG" "$NAT/oss-catalog.json"
  fi
fi

echo "generate-storybook: wrote $OUT (web=$WANT_WEB, native=$WANT_NATIVE)" >&2
