#!/usr/bin/env bash
# generate-design-md.sh — Build a DESIGN.md root document from design artifacts.
# Aggregates tokens, components, screenshots, provider status, and Framer links.
# Usage: generate-design-md.sh <workspace_root> <project_name> > DESIGN.md
set -euo pipefail

ROOT="${1:-.}"
PROJECT="${2:-project}"
COMPONENT_LIB="$ROOT/.tasks/design/component-library.json"
DESIGN_CONTEXT="$ROOT/.tasks/design/design-context.json"
SNAPSHOT_LINKS="$ROOT/.tasks/design/snapshot-links.md"
CANDIDATES="$ROOT/.tasks/design/candidates.normalized.json"
MANIFEST="$ROOT/.tasks/design/manifest.json"
FRAMER_RUN="$ROOT/.tasks/design/framer/framer-run.json"
STITCH_RUN="$ROOT/.tasks/design/stitch/stitch-run.json"
SOURCE_SCREENSHOTS="$ROOT/.tasks/design/source-screenshots.json"

# --- Header ---
cat <<EOF
# Design System — ${PROJECT}

> Auto-generated by the intake pipeline. Aggregates design tokens,
> component inventory, provider artifacts, and visual references.

EOF

# --- Provider Status ---
if [ -f "$CANDIDATES" ]; then
  printf '## Provider Status\n\n'
  printf '| Provider | Target | Status |\n'
  printf '|----------|--------|--------|\n'
  jq -r '.[] | "| \(.provider) | \(.target) | \(.status) |"' "$CANDIDATES" 2>/dev/null
  printf '\n'
fi

# --- Design Mode ---
if [ -f "$DESIGN_CONTEXT" ]; then
  MODE=$(jq -r '.mode // "unknown"' "$DESIGN_CONTEXT" 2>/dev/null)
  PROVIDER_MODE=$(jq -r '.providerMode // "unknown"' "$DESIGN_CONTEXT" 2>/dev/null)
  HAS_FRONTEND=$(jq -r '.hasFrontend // false' "$DESIGN_CONTEXT" 2>/dev/null)
  CONFIDENCE=$(jq -r '.confidence // "N/A"' "$DESIGN_CONTEXT" 2>/dev/null)
  TARGETS=$(jq -r '(.frontendTargets // []) | join(", ")' "$DESIGN_CONTEXT" 2>/dev/null)
  cat <<EOF
**Mode:** ${MODE} · **Provider mode:** ${PROVIDER_MODE} · **Frontend detected:** ${HAS_FRONTEND} · **Confidence:** ${CONFIDENCE}
**Targets:** ${TARGETS:-none}

EOF
fi

# --- Current Site Screenshots ---
printf '## Current Site\n\n'
HAS_SCREENSHOTS=false
if [ -f "$SOURCE_SCREENSHOTS" ]; then
  SCREENSHOT_OUTPUT=$(jq -r '.[] | select(.asset_url != null and .asset_url != "") | "### \(.source_url)\n\n![Screenshot of \(.source_url)](\(.asset_url))\n"' "$SOURCE_SCREENSHOTS" 2>/dev/null || true)
  if [ -n "$SCREENSHOT_OUTPUT" ]; then
    printf '%s\n' "$SCREENSHOT_OUTPUT"
    HAS_SCREENSHOTS=true
  fi
fi
if [ "$HAS_SCREENSHOTS" = false ] && [ -f "$SNAPSHOT_LINKS" ]; then
  # Fall back to snapshot-links.md content (skip the heading)
  sed '1{/^###/d;}' "$SNAPSHOT_LINKS" 2>/dev/null
  printf '\n'
fi

# --- Design Tokens ---
if [ -f "$COMPONENT_LIB" ]; then
  printf '## Design Tokens\n\n'

  # Colors
  COLOR_COUNT=$(jq '.tokens.color | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$COLOR_COUNT" -gt 0 ]; then
    printf '### Colors\n\n'
    printf '| Token | Value | Description |\n'
    printf '|-------|-------|-------------|\n'
    jq -r '.tokens.color[] | "| `\(.name)` | `\(.value)` | \(.description // "—") |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi

  # Typography
  TYPO_COUNT=$(jq '.tokens.typography | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$TYPO_COUNT" -gt 0 ]; then
    printf '### Typography\n\n'
    printf '| Token | Value |\n'
    printf '|-------|-------|\n'
    jq -r '.tokens.typography[] | "| `\(.name)` | `\(.value)` |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi

  # Spacing
  SPACE_COUNT=$(jq '.tokens.spacing | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$SPACE_COUNT" -gt 0 ]; then
    printf '### Spacing\n\n'
    jq -r '.tokens.spacing | map("`\(.name)` = \(.value)") | join(" · ")' "$COMPONENT_LIB" 2>/dev/null
    printf '\n\n'
  fi

  # Radius
  RADIUS_COUNT=$(jq '.tokens.radius | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$RADIUS_COUNT" -gt 0 ]; then
    printf '### Border Radius\n\n'
    jq -r '.tokens.radius | map("`\(.name)` = \(.value)") | join(" · ")' "$COMPONENT_LIB" 2>/dev/null
    printf '\n\n'
  fi
fi

# --- Component Inventory ---
if [ -f "$COMPONENT_LIB" ]; then
  PRIM_COUNT=$(jq '.primitives | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  PAT_COUNT=$(jq '.patterns | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)

  if [ "$PRIM_COUNT" -gt 0 ] || [ "$PAT_COUNT" -gt 0 ]; then
    printf '## Component Inventory\n\n'
  fi

  if [ "$PRIM_COUNT" -gt 0 ]; then
    printf '### Primitives\n\n'
    printf '| Component | States | Providers |\n'
    printf '|-----------|--------|----------|\n'
    jq -r '.primitives[] | "| **\(.name)** | \(.states | length) states | \(.providers // ["—"] | join(", ")) |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi

  if [ "$PAT_COUNT" -gt 0 ]; then
    printf '### Composition Patterns\n\n'
    printf '| Pattern | States | Providers |\n'
    printf '|---------|--------|----------|\n'
    jq -r '.patterns[] | "| **\(.name)** | \(.states | length) states | \(.providers // ["—"] | join(", ")) |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi
fi

# --- Framer Code Components ---
if [ -f "$COMPONENT_LIB" ]; then
  FRAMER_COUNT=$(jq '.framer_code_components | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$FRAMER_COUNT" -gt 0 ]; then
    printf '## Framer Code Components\n\n'
    if [ -f "$FRAMER_RUN" ]; then
      FRAMER_URL=$(jq -r '.projectUrl // empty' "$FRAMER_RUN" 2>/dev/null)
      if [ -n "$FRAMER_URL" ]; then
        printf '🔗 **Framer Project:** [%s](%s)\n\n' "$FRAMER_URL" "$FRAMER_URL"
      fi
    fi
    jq -r '.framer_code_components[] |
      "### `\(.name)`\n\n" +
      "| Prop | Type | Default |\n|------|------|--------|\n" +
      ([.props[] | "| `\(.name)` | \(.type) | \(.default // "—") |"] | join("\n")) +
      "\n\n" +
      if .notes then "_\(.notes)_\n" else "" end
    ' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi
fi

# --- Stitch Variants ---
STITCH_VARIANTS="$ROOT/.tasks/design/stitch/design-variants.json"
if [ -f "$STITCH_VARIANTS" ]; then
  VARIANT_COUNT=$(jq 'length' "$STITCH_VARIANTS" 2>/dev/null || echo 0)
  if [ "$VARIANT_COUNT" -gt 0 ]; then
    printf '## Stitch Design Variants\n\n'
    jq -r '.[] |
      "### \(.variant_name // .name // .id // "Variant")\n\n" +
      if .imageUrl then "![\(.variant_name // "variant")](\(.imageUrl))\n\n" else "" end +
      if .htmlUrl then "🔗 [View in Stitch](\(.htmlUrl))\n\n" else "" end +
      if .device then "**Device:** \(.device)\n" else "" end +
      if .prompt then "**Prompt:** \(.prompt)\n" else "" end +
      "\n"
    ' "$STITCH_VARIANTS" 2>/dev/null
  fi
fi

# --- Candidate Detail ---
if [ -f "$CANDIDATES" ]; then
  GENERATED=$(jq '[.[] | select(.status == "generated")] | length' "$CANDIDATES" 2>/dev/null || echo 0)
  if [ "$GENERATED" -gt 0 ]; then
    printf '## Generated Candidates\n\n'
    jq -r '.[] | select(.status == "generated") |
      "- **\(.provider)** → \(.target)" +
      if .candidate_id then " (`\(.candidate_id)`)" else "" end +
      if .rationale then "\n  > \(.rationale)" else "" end
    ' "$CANDIDATES" 2>/dev/null
    printf '\n\n'
  fi
fi

# --- File Manifest ---
printf '## Artifact Files\n\n'
printf '| File | Description |\n'
printf '|------|-------------|\n'
printf '| `.tasks/design/component-library.json` | Tokens, primitives, patterns, Framer components |\n'
printf '| `.tasks/design/design-context.json` | Full design pipeline context |\n'
printf '| `.tasks/design/design-system.md` | Design system summary |\n'
printf '| `.tasks/design/candidates.normalized.json` | All design candidates with status |\n'
if [ -f "$ROOT/.tasks/design/framer/candidates.json" ]; then
  printf '| `.tasks/design/framer/candidates.json` | Framer-generated candidates |\n'
fi
if [ -f "$ROOT/.tasks/design/stitch/candidates.json" ]; then
  printf '| `.tasks/design/stitch/candidates.json` | Stitch-generated candidates |\n'
fi
if [ -f "$ROOT/.tasks/design/stitch/design-variants.json" ]; then
  printf '| `.tasks/design/stitch/design-variants.json` | Stitch visual variants |\n'
fi
printf '| `.tasks/design/snapshot-links.md` | Screenshot URLs |\n'
printf '| `.tasks/docs/design-brief.md` | Full enhanced PRD |\n'
printf '\n'

printf '---\n'
printf '_Generated by Morgan intake pipeline_\n'
