#!/usr/bin/env bash
# generate-pr-body.sh — Build a rich PR description from pipeline artifacts.
# Usage: generate-pr-body.sh <workspace_root> <project_name> > pr-body.md
set -euo pipefail

ROOT="${1:-.}"
PROJECT="${2:-intake}"
TASKS_JSON="$ROOT/.tasks/tasks/tasks.json"
SUMMARY_JSON="$ROOT/.intake/intake-summary.json"

TASK_COUNT=0
SUBTASK_COUNT=0
PROMPT_COUNT=0
TOTAL_FILES=0

if [ -f "$TASKS_JSON" ]; then
  TASK_COUNT=$(jq 'length' "$TASKS_JSON" 2>/dev/null || echo 0)
  SUBTASK_COUNT=$(jq '[.[].subtasks | length] | add' "$TASKS_JSON" 2>/dev/null || echo 0)
fi
if [ -d "$ROOT/.tasks" ]; then
  PROMPT_COUNT=$(find "$ROOT/.tasks/docs" -name "prompt.md" 2>/dev/null | wc -l | tr -d ' ')
  TOTAL_FILES=$(find "$ROOT/.tasks" -type f 2>/dev/null | wc -l | tr -d ' ')
fi

# Header
cat <<EOF
## 🚀 ${PROJECT} — Intake Pipeline Output

> **Generated by the Morgan intake pipeline (Lobster) — full end-to-end run with agent delegation, deliberation, and multi-model voting.**

---

### 📊 Pipeline Summary

| Metric | Value |
|--------|-------|
| **Parent tasks** | ${TASK_COUNT} |
| **Subtasks** | ${SUBTASK_COUNT} |
| **Total prompt files** | ${PROMPT_COUNT} |
| **Total files** | ${TOTAL_FILES} |
| **Pipeline stages** | PRD → Design Intake → Deliberation → Voting → Complexity Analysis → Task Expansion → Inline Voting → Skills Discovery → Doc/Prompt Fan-out → Scaffold Generation → Git Commit → PR → Linear Sync |

---

### 🤖 Agent Assignments

| Agent | Role | Tasks |
|-------|------|-------|
EOF

# Agent table from tasks.json
if [ -f "$TASKS_JSON" ]; then
  jq -r '
    group_by(.agent) | map({
      agent: .[0].agent,
      task_count: length,
      subtask_count: ([.[].subtasks | length] | add),
      titles: ([.[].title | split(" (")[0]] | join("; "))
    }) | sort_by(-.task_count) | .[] |
    "| **\(.agent)** | \(.task_count) tasks (\(.subtask_count) subtasks) | \(.titles) |"
  ' "$TASKS_JSON" 2>/dev/null || true
fi

# Task breakdown
cat <<'EOF'

---

### 📋 Task Breakdown

EOF

if [ -f "$TASKS_JSON" ]; then
  jq -r '.[] |
    "<details>\n<summary><strong>Task \(.id):</strong> \(.title) <code>(\(.agent // "unassigned"))</code> — \((.subtasks // []) | length) subtasks</summary>\n\n\((.subtasks // []) | map("- " + .title) | join("\n"))\n</details>\n"
  ' "$TASKS_JSON" 2>/dev/null || true
fi

# Repo structure
cat <<'EOF'

---

### 📁 Repository Structure

```
.tasks/
├── docs/
│   ├── design-brief.md              # Architecture decisions from deliberation
│   ├── research-prd.json             # Raw deliberation research bundle
│   ├── scale-tasks.json              # Scaling/growth task analysis
│   ├── security-report.json          # Security audit findings
│   ├── remediation-tasks.json        # Security remediation tasks
│   └── task-{1..N}/                  # Per-task documentation
│       ├── prompt.md                 # Agent implementation prompt
│       ├── prompt.xml                # Structured prompt (XML)
│       ├── acceptance.md             # Acceptance criteria
│       ├── task.md                   # Task description + details
│       ├── decisions.md              # Design decisions for this task
│       └── subtasks/
│           └── task-{id}.{subid}/
│               └── prompt.md         # Subtask implementation prompt
├── tasks/
│   └── tasks.json                    # Full expanded task JSON
└── design/
    ├── design-context.json           # Design discovery context
    └── stitch/                       # Stitch design system artifacts
```
EOF

# Design snapshot links if available
SNAPSHOT_MD="$ROOT/.tasks/design/snapshot-links.md"
if [ -s "$SNAPSHOT_MD" ]; then
  printf '\n---\n\n### 🎨 Design Snapshots\n\n'
  cat "$SNAPSHOT_MD"
fi

# Linear section
cat <<'EOF'

---

### 🔗 Linear Project

All issues are tracked with full agent delegation:
- Each task and subtask has a corresponding Linear issue
- Agent assignment uses Linear's **delegate** model (human as assignee, agent as delegate)
- Issues link back to their prompt files in this PR

---

*Auto-generated by the [CTO intake pipeline](https://github.com/5dlabs/cto) · Lobster*
EOF
