#!/usr/bin/env bash
# generate-design-md.sh — Build a DESIGN.md root document from design artifacts.
# Aggregates tokens, components, screenshots, provider status, and OSS provider links.
# Usage: generate-design-md.sh <workspace_root> <project_name> > DESIGN.md
set -euo pipefail

ROOT="${1:-.}"
PROJECT="${2:-project}"
COMPONENT_LIB="$ROOT/.tasks/design/component-library.json"
DESIGN_CONTEXT="$ROOT/.tasks/design/design-context.json"
SNAPSHOT_LINKS="$ROOT/.tasks/design/snapshot-links.md"
CANDIDATES="$ROOT/.tasks/design/candidates.normalized.json"
MANIFEST="$ROOT/.tasks/design/manifest.json"
STITCH_RUN="$ROOT/.tasks/design/stitch/stitch-run.json"
SOURCE_SCREENSHOTS="$ROOT/.tasks/design/source-screenshots.json"

# --- Header ---
cat <<EOF
# Design System — ${PROJECT}

> Auto-generated by the intake pipeline. Aggregates design tokens,
> component inventory, provider artifacts, and visual references.

EOF

# --- Provider Status ---
if [ -f "$CANDIDATES" ]; then
  printf '## Provider Status\n\n'
  printf '| Provider | Target | Status |\n'
  printf '|----------|--------|--------|\n'
  jq -r '.[] | "| \(.provider) | \(.target) | \(.status) |"' "$CANDIDATES" 2>/dev/null
  printf '\n'
fi

# --- Design Mode ---
if [ -f "$DESIGN_CONTEXT" ]; then
  MODE=$(jq -r '.mode // "unknown"' "$DESIGN_CONTEXT" 2>/dev/null)
  PROVIDER_MODE=$(jq -r '.providerMode // "unknown"' "$DESIGN_CONTEXT" 2>/dev/null)
  HAS_FRONTEND=$(jq -r '.hasFrontend // false' "$DESIGN_CONTEXT" 2>/dev/null)
  CONFIDENCE=$(jq -r '.confidence // "N/A"' "$DESIGN_CONTEXT" 2>/dev/null)
  TARGETS=$(jq -r '(.frontendTargets // []) | join(", ")' "$DESIGN_CONTEXT" 2>/dev/null)
  cat <<EOF
**Mode:** ${MODE} · **Provider mode:** ${PROVIDER_MODE} · **Frontend detected:** ${HAS_FRONTEND} · **Confidence:** ${CONFIDENCE}
**Targets:** ${TARGETS:-none}

EOF
fi

# --- Current Site Screenshots ---
printf '## Current Site\n\n'
HAS_SCREENSHOTS=false
if [ -f "$SOURCE_SCREENSHOTS" ]; then
  SCREENSHOT_OUTPUT=$(jq -r '.[] | select(.asset_url != null and .asset_url != "") | "### \(.source_url)\n\n![Screenshot of \(.source_url)](\(.asset_url))\n"' "$SOURCE_SCREENSHOTS" 2>/dev/null || true)
  if [ -n "$SCREENSHOT_OUTPUT" ]; then
    printf '%s\n' "$SCREENSHOT_OUTPUT"
    HAS_SCREENSHOTS=true
  fi
fi
if [ "$HAS_SCREENSHOTS" = false ] && [ -f "$SNAPSHOT_LINKS" ]; then
  # Fall back to snapshot-links.md content (skip the heading)
  sed '1{/^###/d;}' "$SNAPSHOT_LINKS" 2>/dev/null
  printf '\n'
fi

# --- Design Tokens ---
if [ -f "$COMPONENT_LIB" ]; then
  printf '## Design Tokens\n\n'

  # Colors
  COLOR_COUNT=$(jq '.tokens.color | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$COLOR_COUNT" -gt 0 ]; then
    printf '### Colors\n\n'
    printf '| Token | Value | Description |\n'
    printf '|-------|-------|-------------|\n'
    jq -r '.tokens.color[] | "| `\(.name)` | `\(.value)` | \(.description // "—") |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi

  # Typography
  TYPO_COUNT=$(jq '.tokens.typography | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$TYPO_COUNT" -gt 0 ]; then
    printf '### Typography\n\n'
    printf '| Token | Value |\n'
    printf '|-------|-------|\n'
    jq -r '.tokens.typography[] | "| `\(.name)` | `\(.value)` |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi

  # Spacing
  SPACE_COUNT=$(jq '.tokens.spacing | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$SPACE_COUNT" -gt 0 ]; then
    printf '### Spacing\n\n'
    jq -r '.tokens.spacing | map("`\(.name)` = \(.value)") | join(" · ")' "$COMPONENT_LIB" 2>/dev/null
    printf '\n\n'
  fi

  # Radius
  RADIUS_COUNT=$(jq '.tokens.radius | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  if [ "$RADIUS_COUNT" -gt 0 ]; then
    printf '### Border Radius\n\n'
    jq -r '.tokens.radius | map("`\(.name)` = \(.value)") | join(" · ")' "$COMPONENT_LIB" 2>/dev/null
    printf '\n\n'
  fi
fi

# --- Component Inventory ---
if [ -f "$COMPONENT_LIB" ]; then
  PRIM_COUNT=$(jq '.primitives | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)
  PAT_COUNT=$(jq '.patterns | length' "$COMPONENT_LIB" 2>/dev/null || echo 0)

  if [ "$PRIM_COUNT" -gt 0 ] || [ "$PAT_COUNT" -gt 0 ]; then
    printf '## Component Inventory\n\n'
  fi

  if [ "$PRIM_COUNT" -gt 0 ]; then
    printf '### Primitives\n\n'
    printf '| Component | States | Providers |\n'
    printf '|-----------|--------|----------|\n'
    jq -r '.primitives[] | "| **\(.name)** | \(.states | length) states | \(.providers // ["—"] | join(", ")) |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi

  if [ "$PAT_COUNT" -gt 0 ]; then
    printf '### Composition Patterns\n\n'
    printf '| Pattern | States | Providers |\n'
    printf '|---------|--------|----------|\n'
    jq -r '.patterns[] | "| **\(.name)** | \(.states | length) states | \(.providers // ["—"] | join(", ")) |"' "$COMPONENT_LIB" 2>/dev/null
    printf '\n'
  fi
fi

# --- Stitch Mockups (repo-local PNGs) ---
# Prefer rendering mockups from .tasks/design/mockups/ so reviewers can see them
# directly on GitHub without authenticating to Stitch or Linear.
MOCKUPS_DIR="$ROOT/.tasks/design/mockups"
MOCKUPS_MANIFEST="$MOCKUPS_DIR/manifest.json"
HAS_LOCAL_MOCKUPS=false
if [ -d "$MOCKUPS_DIR" ]; then
  if compgen -G "$MOCKUPS_DIR/*.png" > /dev/null; then
    HAS_LOCAL_MOCKUPS=true
  fi
fi

if [ "$HAS_LOCAL_MOCKUPS" = true ]; then
  printf '## Stitch Mockups\n\n'
  printf '> Screenshots captured from Stitch HTML mockups. Click "View in Stitch"\n'
  printf '> to open the live, interactive version (auth required).\n\n'
  if [ -f "$MOCKUPS_MANIFEST" ]; then
    jq -r '
      sort_by(.index) | .[] |
      select((.png // "") != "") |
      "### Mockup \(.index): \(.target) (\(.device))\n\n" +
      "![\(.target) — \(.device)](./mockups/\(.png))\n\n" +
      "**Screen:** `\(.screenId)`\n\n" +
      (if (.rationale // "") != "" then "> \(.rationale)\n\n" else "" end) +
      (if (.htmlUrl // "") != "" then "🔗 [View in Stitch](\(.htmlUrl))\n\n" else "" end)
    ' "$MOCKUPS_MANIFEST" 2>/dev/null
  else
    # No manifest — embed every PNG with a generic label.
    for png in "$MOCKUPS_DIR"/*.png; do
      [ -f "$png" ] || continue
      filename=$(basename "$png")
      label="${filename%.png}"
      printf '### %s\n\n![%s](./mockups/%s)\n\n' "$label" "$label" "$filename"
    done
  fi
fi

# --- Stitch Variants (legacy / remote) ---
STITCH_VARIANTS="$ROOT/.tasks/design/stitch/design-variants.json"
if [ -f "$STITCH_VARIANTS" ] && [ "$HAS_LOCAL_MOCKUPS" = false ]; then
  VARIANT_COUNT=$(jq 'length' "$STITCH_VARIANTS" 2>/dev/null || echo 0)
  if [ "$VARIANT_COUNT" -gt 0 ]; then
    printf '## Stitch Design Variants\n\n'
    jq -r '.[] |
      "### \(.variant_name // .name // .id // "Variant")\n\n" +
      if .imageUrl then "![\(.variant_name // "variant")](\(.imageUrl))\n\n" else "" end +
      if .htmlUrl then "🔗 [View in Stitch](\(.htmlUrl))\n\n" else "" end +
      if .device then "**Device:** \(.device)\n" else "" end +
      if .prompt then "**Prompt:** \(.prompt)\n" else "" end +
      "\n"
    ' "$STITCH_VARIANTS" 2>/dev/null
  fi
fi

# --- Candidate Detail ---
if [ -f "$CANDIDATES" ]; then
  GENERATED=$(jq '[.[] | select(.status == "generated")] | length' "$CANDIDATES" 2>/dev/null || echo 0)
  if [ "$GENERATED" -gt 0 ]; then
    printf '## Generated Candidates\n\n'
    jq -r '.[] | select(.status == "generated") |
      "- **\(.provider)** → \(.target)" +
      if .candidate_id then " (`\(.candidate_id)`)" else "" end +
      if .rationale then "\n  > \(.rationale)" else "" end
    ' "$CANDIDATES" 2>/dev/null
    printf '\n\n'
  fi
fi

# --- File Manifest ---
printf '## Artifact Files\n\n'
printf '| File | Description |\n'
printf '|------|-------------|\n'
printf '| `.tasks/design/component-library.json` | Tokens, primitives, patterns, component map |\n'
printf '| `.tasks/design/design-context.json` | Full design pipeline context |\n'
printf '| `.tasks/design/design-system.md` | Design system summary |\n'
printf '| `.tasks/design/candidates.normalized.json` | All design candidates with status |\n'
if [ -f "$ROOT/.tasks/design/stitch/candidates.json" ]; then
  printf '| `.tasks/design/stitch/candidates.json` | Stitch-generated candidates |\n'
fi
if [ -f "$ROOT/.tasks/design/stitch/design-variants.json" ]; then
  printf '| `.tasks/design/stitch/design-variants.json` | Stitch visual variants |\n'
fi
if [ -d "$ROOT/.tasks/design/mockups" ]; then
  printf '| `.tasks/design/mockups/` | Repo-local PNG screenshots of Stitch mockups |\n'
fi
printf '| `.tasks/design/snapshot-links.md` | Screenshot URLs |\n'
printf '| `.tasks/docs/design-brief.md` | Full enhanced PRD |\n'
printf '\n'

printf '---\n'
printf '_Generated by Morgan intake pipeline_\n'
