#!/usr/bin/env bash
# upload-deliberation-release.sh — Create a GitHub release on the target repo
# with deliberation MP3(s) attached.
#
# Usage: upload-deliberation-release.sh <workspace_root> <target_repo_path> <project_name> <pr_url>
#
# Outputs JSON: {"release_url":"...","tag":"...","assets":[...]}
# If no MP3 files are found or gh CLI is missing, exits 0 with {"release_url":"none"}.
set -euo pipefail

ROOT="${1:?missing workspace root}"
TARGET="${2:?missing target repo path}"
PROJECT="${3:?missing project name}"
PR_URL="${4:-}"

# Collect MP3 files from .tasks/audio/
AUDIO_DIR="$ROOT/.tasks/audio"
AUDIO_FILES=()
for f in "$AUDIO_DIR"/*.mp3; do
  [ -f "$f" ] && AUDIO_FILES+=("$f")
done
for f in "$AUDIO_DIR"/*.transcript.json; do
  [ -f "$f" ] && AUDIO_FILES+=("$f")
done

if [ ${#AUDIO_FILES[@]} -eq 0 ]; then
  echo "upload-deliberation-release: no audio files found in $AUDIO_DIR" >&2
  printf '{"release_url":"none","reason":"no_audio_files"}\n'
  exit 0
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "upload-deliberation-release: gh CLI not available" >&2
  printf '{"release_url":"none","reason":"gh_missing"}\n'
  exit 0
fi

# Derive owner/repo from target repo remote
REPO_SLUG="$(git -C "$TARGET" remote get-url origin 2>/dev/null \
  | sed 's|.*github\.com[:/]||; s|\.git$||')"
if [ -z "$REPO_SLUG" ]; then
  echo "upload-deliberation-release: cannot determine repo slug from $TARGET" >&2
  printf '{"release_url":"none","reason":"no_remote"}\n'
  exit 0
fi

TAG="intake-${PROJECT}-$(date +%Y%m%d-%H%M%S)"
TITLE="🎧 ${PROJECT} — Deliberation Audio"

# Build release notes
NOTES="## Deliberation Audio for ${PROJECT}\n\n"
NOTES+="Generated by the Morgan intake pipeline.\n\n"
NOTES+="### Audio Files\n\n"
for f in "${AUDIO_FILES[@]}"; do
  BASENAME="$(basename "$f")"
  SIZE="$(du -h "$f" | cut -f1 | tr -d ' ')"
  NOTES+="- **${BASENAME}** (${SIZE})\n"
done
if [ -n "$PR_URL" ] && [ "$PR_URL" != "none" ]; then
  NOTES+="\n### Related\n\n- PR: ${PR_URL}\n"
fi

# Create the release with assets
ASSET_ARGS=()
for f in "${AUDIO_FILES[@]}"; do
  ASSET_ARGS+=("$f")
done

echo "upload-deliberation-release: creating release $TAG on $REPO_SLUG" >&2
RELEASE_OUTPUT="$(gh release create "$TAG" \
  --repo "$REPO_SLUG" \
  --title "$TITLE" \
  --notes "$(printf '%b' "$NOTES")" \
  --latest=false \
  "${ASSET_ARGS[@]}" 2>&1)" || {
  echo "upload-deliberation-release: gh release create failed: $RELEASE_OUTPUT" >&2
  printf '{"release_url":"none","reason":"release_failed","error":"%s"}\n' \
    "$(printf '%s' "$RELEASE_OUTPUT" | tr '"' "'")"
  exit 0
}

RELEASE_URL="$(printf '%s' "$RELEASE_OUTPUT" | grep -o 'https://[^ ]*' | head -1)"
if [ -z "$RELEASE_URL" ]; then
  RELEASE_URL="https://github.com/${REPO_SLUG}/releases/tag/${TAG}"
fi

echo "upload-deliberation-release: release created → $RELEASE_URL" >&2

# Build asset URLs
ASSETS_JSON="["
FIRST=true
for f in "${AUDIO_FILES[@]}"; do
  BASENAME="$(basename "$f")"
  ASSET_URL="https://github.com/${REPO_SLUG}/releases/download/${TAG}/${BASENAME}"
  if [ "$FIRST" = true ]; then
    FIRST=false
  else
    ASSETS_JSON+=","
  fi
  ASSETS_JSON+="{\"name\":\"${BASENAME}\",\"url\":\"${ASSET_URL}\"}"
done
ASSETS_JSON+="]"

jq -nc \
  --arg release_url "$RELEASE_URL" \
  --arg tag "$TAG" \
  --argjson assets "$ASSETS_JSON" \
  '{release_url:$release_url,tag:$tag,assets:$assets}'
