---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - remote-network.yaml
  - connector.yaml
  - network-resource.yaml

# Common labels
labels:
  - pairs:
      app.kubernetes.io/name: twingate
      app.kubernetes.io/part-of: networking
      app.kubernetes.io/managed-by: argocd
