---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

resources:
  - pod-network.yaml
  - service-network.yaml
  - openclaw-tool-server.yaml
  - pod-network-access.yaml
  - service-network-access.yaml
  - openclaw-tool-server-access.yaml

labels:
  - pairs:
      app.kubernetes.io/name: twingate
      app.kubernetes.io/part-of: networking
      app.kubernetes.io/managed-by: argocd
