---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: openclaw-tool-server-everyone
spec:
  resourceRef:
    name: openclaw-tool-server
    namespace: operators
  principalId: R3JvdXA6NzQ2MDQy
