---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: cto-service-network-everyone
spec:
  resourceRef:
    name: cto-service-network
    namespace: operators
  principalId: R3JvdXA6NzQ2MDQy
