---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data
  namespace: messaging
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/component: push-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor
  resources:
    requests:
      storage: 5Gi
